#ifndef _MANAGEDGENERICIRPSYSTEM_IDL_
#define _MANAGEDGENERICIRPSYSTEM_IDL_

// This statement must appear after all include statements
#pragma prefix "3gppsa5.org"

/* ## Module: ManagedGenericIRPSystem
This module contains definitions commonly used among all IRPs such as Alarm IRP.
================================================================
*/
module ManagedGenericIRPSystem
{
   /*
   Exception thrown when an unsupported optional parameter 
   is passed with information.
   The parameter shall be the actual unsupported parameter name.
   */
   exception ParameterNotSupported { string parameter; };

   /*
   Exception thrown when an invalid parameter value is passed.
   The parameter shall be the actual parameter name.
   */
   exception InvalidParameter { string parameter; };

   /*
   Exception thrown when a valid but unsupported parameter value is passed.
   The parameter shall be the actual parameter name.
   */
   exception ValueNotSupported { string parameter; };

   /*
   Exception thrown when an unsupported optional method is called.
   */
   exception OperationNotSupported {};
};

#endif  // _MANAGEDGENERICIRPSYSTEM_IDL_
