package ConfigExtended;


/**
* ConfigExtended/ConfigNotificationSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_ext_G.idl
* Friday, June 1, 2018 12:05:52 PM GMT+01:00
*/

abstract public class ConfigNotificationSeqHelper
{
  private static String  _id = "IDL:ConfigExtended/ConfigNotificationSeq:1.0";

  public static void insert (org.omg.CORBA.Any a, ConfigExtended.ConfigNotification[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ConfigExtended.ConfigNotification[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = ConfigExtended.ConfigNotificationHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (ConfigExtended.ConfigNotificationSeqHelper.id (), "ConfigNotificationSeq", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ConfigExtended.ConfigNotification[] read (org.omg.CORBA.portable.InputStream istream)
  {
    ConfigExtended.ConfigNotification value[] = null;
    int _len0 = istream.read_long ();
    value = new ConfigExtended.ConfigNotification[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = ConfigExtended.ConfigNotificationHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ConfigExtended.ConfigNotification[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      ConfigExtended.ConfigNotificationHelper.write (ostream, value[_i0]);
  }

}
