package ConfigExtended;


/**
* ConfigExtended/MOInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_ext_G.idl
* Friday, June 1, 2018 12:05:52 PM GMT+01:00
*/

public final class MOInfo implements org.omg.CORBA.portable.IDLEntity
{
  public long moId = (long)0;
  public String type = null;
  public String localDN = null;
  public String prefix = null;

  public MOInfo ()
  {
  } // ctor

  public MOInfo (long _moId, String _type, String _localDN, String _prefix)
  {
    moId = _moId;
    type = _type;
    localDN = _localDN;
    prefix = _prefix;
  } // ctor

} // class MOInfo
