package FMEvent;


/**
* FMEvent/NV_SPECIFIC_EVENT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FmEvent_F.idl
* Wednesday, July 11, 2018 2:25:11 PM GMT+01:00
*/

public interface NV_SPECIFIC_EVENT
{

  /*
    This block encapsulates string used in the name of the Name Value
    pair of the structured event.
    */
  public static final String value = "z";
}
