package CosNotification;


/**
* CosNotification/BestEffort.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification_F.idl
* Wednesday, July 11, 2018 2:25:09 PM GMT+01:00
*/

public interface BestEffort
{
  public static final short value = (short)(0);
}
