package CosNotification;


/**
* CosNotification/ConnectionReliability.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification_F.idl
* Wednesday, July 11, 2018 2:25:09 PM GMT+01:00
*/

public interface ConnectionReliability
{
  public static final String value = "ConnectionReliability";
}
