package CosNotification;


/**
* CosNotification/EventType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification_F.idl
* Wednesday, July 11, 2018 2:25:09 PM GMT+01:00
*/

public final class EventType implements org.omg.CORBA.portable.IDLEntity
{
  public String domain_name = null;
  public String type_name = null;

  public EventType ()
  {
  } // ctor

  public EventType (String _domain_name, String _type_name)
  {
    domain_name = _domain_name;
    type_name = _type_name;
  } // ctor

} // class EventType
