package CosNotification;


/**
* CosNotification/MaxEventsPerConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification_F.idl
* Wednesday, July 11, 2018 2:25:09 PM GMT+01:00
*/

public interface MaxEventsPerConsumer
{

  // StopTimeSupported takes on a boolean value
  public static final String value = "MaxEventsPerConsumer";
}
