package CosNotification;


/**
* CosNotification/MaxQueueLength.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification_F.idl
* Wednesday, July 11, 2018 2:25:09 PM GMT+01:00
*/

public interface MaxQueueLength
{

  // message quality of service
  public static final String value = "MaxQueueLength";
}
