package CosNotification;


/**
* CosNotification/RejectNewEvents.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification_F.idl
* Wednesday, July 11, 2018 2:25:09 PM GMT+01:00
*/

public interface RejectNewEvents
{

  // MaxSuppliers takes on a value of type long
  public static final String value = "RejectNewEvents";
}
