package CosNotification;


/**
* CosNotification/StartTimeSupported.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification_F.idl
* Wednesday, July 11, 2018 2:25:09 PM GMT+01:00
*/

public interface StartTimeSupported
{

  // PacingInterval takes on a value of type TimeBase::TimeT
  public static final String value = "StartTimeSupported";
}
