package PerformanceIRPConstDefs;


/**
* PerformanceIRPConstDefs/AttrType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PerformanceIRPConstDefs_F.idl
* Thursday, June 21, 2018 8:22:15 AM GMT+01:00
*/

public class AttrType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static PerformanceIRPConstDefs.AttrType[] __array = new PerformanceIRPConstDefs.AttrType [__size];

  public static final int _INTEGER_ATTR = 0;
  public static final PerformanceIRPConstDefs.AttrType INTEGER_ATTR = new PerformanceIRPConstDefs.AttrType(_INTEGER_ATTR);
  public static final int _REAL_ATTR = 1;
  public static final PerformanceIRPConstDefs.AttrType REAL_ATTR = new PerformanceIRPConstDefs.AttrType(_REAL_ATTR);

  public int value ()
  {
    return __value;
  }

  public static PerformanceIRPConstDefs.AttrType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected AttrType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class AttrType
