package PerformanceIRPConstDefs;

/**
* PerformanceIRPConstDefs/FilterableDataValueHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PerformanceIRPConstDefs_F.idl
* Thursday, June 21, 2018 8:22:15 AM GMT+01:00
*/


//## Category: Const_Declarations
public final class FilterableDataValueHolder implements org.omg.CORBA.portable.Streamable
{
  public PerformanceIRPConstDefs.FilterableDataValue value = null;

  public FilterableDataValueHolder ()
  {
  }

  public FilterableDataValueHolder (PerformanceIRPConstDefs.FilterableDataValue initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PerformanceIRPConstDefs.FilterableDataValueHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PerformanceIRPConstDefs.FilterableDataValueHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PerformanceIRPConstDefs.FilterableDataValueHelper.type ();
  }

}
