package PerformanceIRPConstDefs;

/**
* PerformanceIRPConstDefs/PerformanceMonitoringStateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PerformanceIRPConstDefs_F.idl
* Thursday, June 21, 2018 8:22:15 AM GMT+01:00
*/

public final class PerformanceMonitoringStateHolder implements org.omg.CORBA.portable.Streamable
{
  public PerformanceIRPConstDefs.PerformanceMonitoringState value = null;

  public PerformanceMonitoringStateHolder ()
  {
  }

  public PerformanceMonitoringStateHolder (PerformanceIRPConstDefs.PerformanceMonitoringState initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PerformanceIRPConstDefs.PerformanceMonitoringStateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PerformanceIRPConstDefs.PerformanceMonitoringStateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PerformanceIRPConstDefs.PerformanceMonitoringStateHelper.type ();
  }

}
