package PerformanceIRPConstDefs;


/**
* PerformanceIRPConstDefs/PerformanceMonitoringReportHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PerformanceIRPConstDefs_F.idl
* Thursday, June 21, 2018 8:22:15 AM GMT+01:00
*/

abstract public class PerformanceMonitoringReportHelper
{
  private static String  _id = "IDL:PerformanceIRPConstDefs/PerformanceMonitoringReport/PerformanceMonitoringReport:1.0";

  public static void insert (org.omg.CORBA.Any a, PerformanceIRPConstDefs.PerformanceMonitoringReport that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PerformanceIRPConstDefs.PerformanceMonitoringReport extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [9];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (PerformanceIRPConstDefs.PerformanceMonitoringIdHelper.id (), "PerformanceMonitoringId", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "performance_monitoring_id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "sequence_number",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulonglong);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (TimeBase.TimeTHelper.id (), "TimeT", _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "scan_initiation_time",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (PerformanceIRPConstDefs.TimePeriodInSecondsHelper.id (), "TimePeriodInSeconds", _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "granularity_period",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (PerformanceIRPConstDefs.InstanceListHelper.id (), "InstanceList", _tcOf_members0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "instance_list",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (PerformanceIRPConstDefs.AttributeListHelper.id (), "AttributeList", _tcOf_members0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "attribute_list",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[6] = new org.omg.CORBA.StructMember (
            "observed_values",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (PerformanceIRPConstDefs.TimePeriodInSecondsHelper.id (), "TimePeriodInSeconds", _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[7] = new org.omg.CORBA.StructMember (
            "time_stamp",
            _tcOf_members0,
            null);
          _tcOf_members0 = PerformanceIRPConstDefs.SuspectFlagHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[8] = new org.omg.CORBA.StructMember (
            "suspect_flag",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (PerformanceIRPConstDefs.PerformanceMonitoringReportHelper.id (), "PerformanceMonitoringReport", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PerformanceIRPConstDefs.PerformanceMonitoringReport read (org.omg.CORBA.portable.InputStream istream)
  {
    PerformanceIRPConstDefs.PerformanceMonitoringReport value = new PerformanceIRPConstDefs.PerformanceMonitoringReport ();
    value.performance_monitoring_id = istream.read_long ();
    value.sequence_number = istream.read_long ();
    value.scan_initiation_time = istream.read_ulonglong ();
    value.granularity_period = istream.read_long ();
    value.instance_list = PerformanceIRPConstDefs.InstanceListHelper.read (istream);
    value.attribute_list = PerformanceIRPConstDefs.AttributeListHelper.read (istream);
    int _len0 = istream.read_long ();
    value.observed_values = new int[_len0];
    istream.read_long_array (value.observed_values, 0, _len0);
    int _len1 = istream.read_long ();
    value.time_stamp = new int[_len1];
    for (int _o2 = 0;_o2 < value.time_stamp.length; ++_o2)
      value.time_stamp[_o2] = PerformanceIRPConstDefs.TimePeriodInSecondsHelper.read (istream);
    int _len2 = istream.read_long ();
    value.suspect_flag = new PerformanceIRPConstDefs.SuspectFlag[_len2];
    for (int _o3 = 0;_o3 < value.suspect_flag.length; ++_o3)
      value.suspect_flag[_o3] = PerformanceIRPConstDefs.SuspectFlagHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PerformanceIRPConstDefs.PerformanceMonitoringReport value)
  {
    ostream.write_long (value.performance_monitoring_id);
    ostream.write_long (value.sequence_number);
    ostream.write_ulonglong (value.scan_initiation_time);
    ostream.write_long (value.granularity_period);
    PerformanceIRPConstDefs.InstanceListHelper.write (ostream, value.instance_list);
    PerformanceIRPConstDefs.AttributeListHelper.write (ostream, value.attribute_list);
    ostream.write_long (value.observed_values.length);
    ostream.write_long_array (value.observed_values, 0, value.observed_values.length);
    ostream.write_long (value.time_stamp.length);
    for (int _i0 = 0;_i0 < value.time_stamp.length; ++_i0)
      PerformanceIRPConstDefs.TimePeriodInSecondsHelper.write (ostream, value.time_stamp[_i0]);
    ostream.write_long (value.suspect_flag.length);
    for (int _i1 = 0;_i1 < value.suspect_flag.length; ++_i1)
      PerformanceIRPConstDefs.SuspectFlagHelper.write (ostream, value.suspect_flag[_i1]);
  }

}
