package PerformanceIRPConstDefs;


/**
* PerformanceIRPConstDefs/PerformanceEvent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PerformanceIRPConstDefs_F.idl
* Thursday, June 21, 2018 8:22:15 AM GMT+01:00
*/

public final class PerformanceEvent implements org.omg.CORBA.portable.IDLEntity
{
  public String observed_object_instance = null;
  public PerformanceIRPConstDefs.EventCategory event_category = null;
  public int event_id = (int)0;
  public String attribute_name[] = null;
  public int attribute_value[] = null;
  public PerformanceIRPConstDefs.SuspectFlag suspect_flag[] = null;
  public long event_time = (long)0;
  public String additional_info_name[] = null;
  public org.omg.CORBA.Any additional_info_value[] = null;

  public PerformanceEvent ()
  {
  } // ctor

  public PerformanceEvent (String _observed_object_instance, PerformanceIRPConstDefs.EventCategory _event_category, int _event_id, String[] _attribute_name, int[] _attribute_value, PerformanceIRPConstDefs.SuspectFlag[] _suspect_flag, long _event_time, String[] _additional_info_name, org.omg.CORBA.Any[] _additional_info_value)
  {
    observed_object_instance = _observed_object_instance;
    event_category = _event_category;
    event_id = _event_id;
    attribute_name = _attribute_name;
    attribute_value = _attribute_value;
    suspect_flag = _suspect_flag;
    event_time = _event_time;
    additional_info_name = _additional_info_name;
    additional_info_value = _additional_info_value;
  } // ctor

} // class PerformanceEvent
