package CelloAlarmIRPExtension;


/**
* CelloAlarmIRPExtension/AlarmIRPExtensionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CelloAlarmIRPExtension_F.idl
* Wednesday, July 11, 2018 2:25:07 PM GMT+01:00
*/


/*
   * This interface extends the Alarm IRP with Cello specific support
   * for alarm filtering and configuration of severity.
   *
   */
public interface AlarmIRPExtensionOperations  extends AlarmIRPSystem.AlarmIRPOperationsOperations
{

  /*
       * Returns alarm information based on a filter.
       * Severity is the only filter parameter that is validated.
       *
       */
  CosNotification.StructuredEvent[] get_alarm_list_ext (CelloAlarmIRPExtension.FilterType filter) throws CelloAlarmIRPExtension.GetAlarmListExt, AlarmIRPSystem.InvalidParameter;

  /*
       * Returns the number of active alarms based on a filter.
       * The result is divided into perceived severity.
       * Severity is the only filter parameter that is validated.
       *
       */
  void get_alarm_count_ext (CelloAlarmIRPExtension.FilterType filter, org.omg.CORBA.IntHolder critical_count, org.omg.CORBA.IntHolder major_count, org.omg.CORBA.IntHolder minor_count, org.omg.CORBA.IntHolder warning_count, org.omg.CORBA.IntHolder indeterminate_count, org.omg.CORBA.IntHolder cleared_count) throws CelloAlarmIRPExtension.GetAlarmCountExt, AlarmIRPSystem.InvalidParameter;

  /*
       * Re-defines the severity for a specific problem.
       * No validation is performed for to discover not
       * used specific problem.
       *
       */
  void set_severity (String specific_problem, short severity) throws CelloAlarmIRPExtension.SetSeverity, AlarmIRPSystem.InvalidParameter;

  /*
       * Returns a list containing all re-definitions of perceived severity.
       *
       */
  CelloAlarmIRPExtension.SeverityInfo[] get_all_modified_severity () throws CelloAlarmIRPExtension.GetAllModifiedSeverity;

  /*
       * Deletes a severity configuration for one or several specific problems.
       *
       */
  void remove_severity_configuration (String[] spec_problem_list) throws CelloAlarmIRPExtension.RemoveSeverityConfiguration;
} // interface AlarmIRPExtensionOperations
