package CelloAlarmIRPExtension;

/**
* CelloAlarmIRPExtension/SetSeverityHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CelloAlarmIRPExtension_F.idl
* Wednesday, July 11, 2018 2:25:07 PM GMT+01:00
*/

public final class SetSeverityHolder implements org.omg.CORBA.portable.Streamable
{
  public CelloAlarmIRPExtension.SetSeverity value = null;

  public SetSeverityHolder ()
  {
  }

  public SetSeverityHolder (CelloAlarmIRPExtension.SetSeverity initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CelloAlarmIRPExtension.SetSeverityHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CelloAlarmIRPExtension.SetSeverityHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CelloAlarmIRPExtension.SetSeverityHelper.type ();
  }

}
