package PerformanceIRPConstDefs;


/**
* PerformanceIRPConstDefs/AttrValueHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PerformanceIRPConstDefs_F.idl
* Thursday, June 21, 2018 8:22:15 AM GMT+01:00
*/

abstract public class AttrValueHelper
{
  private static String  _id = "IDL:PerformanceIRPConstDefs/AttrValue/AttrValue:1.0";

  public static void insert (org.omg.CORBA.Any a, PerformanceIRPConstDefs.AttrValue that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PerformanceIRPConstDefs.AttrValue extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      org.omg.CORBA.TypeCode _disTypeCode0;
      _disTypeCode0 = PerformanceIRPConstDefs.AttrTypeHelper.type ();
      org.omg.CORBA.UnionMember[] _members0 = new org.omg.CORBA.UnionMember [2];
      org.omg.CORBA.TypeCode _tcOf_members0;
      org.omg.CORBA.Any _anyOf_members0;

      // Branch for i_attribute (case label INTEGER_ATTR)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      PerformanceIRPConstDefs.AttrTypeHelper.insert (_anyOf_members0, PerformanceIRPConstDefs.AttrType.INTEGER_ATTR);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
      _members0[0] = new org.omg.CORBA.UnionMember (
        "i_attribute",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for r_attribute (case label REAL_ATTR)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      PerformanceIRPConstDefs.AttrTypeHelper.insert (_anyOf_members0, PerformanceIRPConstDefs.AttrType.REAL_ATTR);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
      _members0[1] = new org.omg.CORBA.UnionMember (
        "r_attribute",
        _anyOf_members0,
        _tcOf_members0,
        null);
      __typeCode = org.omg.CORBA.ORB.init ().create_union_tc (PerformanceIRPConstDefs.AttrValueHelper.id (), "AttrValue", _disTypeCode0, _members0);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PerformanceIRPConstDefs.AttrValue read (org.omg.CORBA.portable.InputStream istream)
  {
    PerformanceIRPConstDefs.AttrValue value = new PerformanceIRPConstDefs.AttrValue ();
    PerformanceIRPConstDefs.AttrType _dis0 = null;
    _dis0 = PerformanceIRPConstDefs.AttrTypeHelper.read (istream);
    switch (_dis0.value ())
    {
      case PerformanceIRPConstDefs.AttrType._INTEGER_ATTR:
        int _i_attribute = (int)0;
        _i_attribute = istream.read_long ();
        value.i_attribute (_i_attribute);
        break;
      case PerformanceIRPConstDefs.AttrType._REAL_ATTR:
        double _r_attribute = (double)0;
        _r_attribute = istream.read_double ();
        value.r_attribute (_r_attribute);
        break;
    }
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PerformanceIRPConstDefs.AttrValue value)
  {
    PerformanceIRPConstDefs.AttrTypeHelper.write (ostream, value.discriminator ());
    switch (value.discriminator ().value ())
    {
      case PerformanceIRPConstDefs.AttrType._INTEGER_ATTR:
        ostream.write_long (value.i_attribute ());
        break;
      case PerformanceIRPConstDefs.AttrType._REAL_ATTR:
        ostream.write_double (value.r_attribute ());
        break;
    }
  }

}
