package PerformanceIRPConstDefs;


/**
* PerformanceIRPConstDefs/Direction.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PerformanceIRPConstDefs_F.idl
* Thursday, June 21, 2018 8:22:15 AM GMT+01:00
*/

public class Direction implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static PerformanceIRPConstDefs.Direction[] __array = new PerformanceIRPConstDefs.Direction [__size];

  public static final int _RISING = 0;
  public static final PerformanceIRPConstDefs.Direction RISING = new PerformanceIRPConstDefs.Direction(_RISING);
  public static final int _FALLING = 1;
  public static final PerformanceIRPConstDefs.Direction FALLING = new PerformanceIRPConstDefs.Direction(_FALLING);

  public int value ()
  {
    return __value;
  }

  public static PerformanceIRPConstDefs.Direction from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Direction (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Direction
