package PerformanceIRPConstDefs;


/**
* PerformanceIRPConstDefs/DomainNameValueOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PerformanceIRPConstDefs_F.idl
* Thursday, June 21, 2018 8:22:15 AM GMT+01:00
*/


//## Category: Const_Declarations
public interface DomainNameValueOperations 
{
} // interface DomainNameValueOperations
