package PerformanceIRPConstDefs;


/**
* PerformanceIRPConstDefs/DomainNameValueHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PerformanceIRPConstDefs_F.idl
* Thursday, June 21, 2018 8:22:15 AM GMT+01:00
*/


//## Category: Const_Declarations
abstract public class DomainNameValueHelper
{
  private static String  _id = "IDL:PerformanceIRPConstDefs/DomainNameValue:1.0";

  public static void insert (org.omg.CORBA.Any a, PerformanceIRPConstDefs.DomainNameValue that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PerformanceIRPConstDefs.DomainNameValue extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (PerformanceIRPConstDefs.DomainNameValueHelper.id (), "DomainNameValue");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PerformanceIRPConstDefs.DomainNameValue read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DomainNameValueStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PerformanceIRPConstDefs.DomainNameValue value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static PerformanceIRPConstDefs.DomainNameValue narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PerformanceIRPConstDefs.DomainNameValue)
      return (PerformanceIRPConstDefs.DomainNameValue)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PerformanceIRPConstDefs._DomainNameValueStub stub = new PerformanceIRPConstDefs._DomainNameValueStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static PerformanceIRPConstDefs.DomainNameValue unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PerformanceIRPConstDefs.DomainNameValue)
      return (PerformanceIRPConstDefs.DomainNameValue)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PerformanceIRPConstDefs._DomainNameValueStub stub = new PerformanceIRPConstDefs._DomainNameValueStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
