package PerformanceIRPConstDefs;


/**
* PerformanceIRPConstDefs/ObservationObject.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PerformanceIRPConstDefs_F.idl
* Thursday, June 21, 2018 8:22:15 AM GMT+01:00
*/

public final class ObservationObject implements org.omg.CORBA.portable.IDLEntity
{

  // Attributes
  public String instance_list[] = null;
  public String instance_attribute_list[] = null;

  public ObservationObject ()
  {
  } // ctor

  public ObservationObject (String[] _instance_list, String[] _instance_attribute_list)
  {
    instance_list = _instance_list;
    instance_attribute_list = _instance_attribute_list;
  } // ctor

} // class ObservationObject
