package PerformanceIRPConstDefs;


/**
* PerformanceIRPConstDefs/PerformanceMonitoringListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PerformanceIRPConstDefs_F.idl
* Thursday, June 21, 2018 8:22:15 AM GMT+01:00
*/

abstract public class PerformanceMonitoringListHelper
{
  private static String  _id = "IDL:PerformanceIRPConstDefs/PerformanceMonitoringList:1.0";

  public static void insert (org.omg.CORBA.Any a, PerformanceIRPConstDefs.PerformanceMonitoring[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PerformanceIRPConstDefs.PerformanceMonitoring[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = PerformanceIRPConstDefs.PerformanceMonitoringHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (PerformanceIRPConstDefs.PerformanceMonitoringListHelper.id (), "PerformanceMonitoringList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PerformanceIRPConstDefs.PerformanceMonitoring[] read (org.omg.CORBA.portable.InputStream istream)
  {
    PerformanceIRPConstDefs.PerformanceMonitoring value[] = null;
    int _len0 = istream.read_long ();
    value = new PerformanceIRPConstDefs.PerformanceMonitoring[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = PerformanceIRPConstDefs.PerformanceMonitoringHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PerformanceIRPConstDefs.PerformanceMonitoring[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      PerformanceIRPConstDefs.PerformanceMonitoringHelper.write (ostream, value[_i0]);
  }

}
