package PerformanceIRPConstDefs;


/**
* PerformanceIRPConstDefs/PerformanceMonitoringState.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PerformanceIRPConstDefs_F.idl
* Thursday, June 21, 2018 8:22:15 AM GMT+01:00
*/

public class PerformanceMonitoringState implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static PerformanceIRPConstDefs.PerformanceMonitoringState[] __array = new PerformanceIRPConstDefs.PerformanceMonitoringState [__size];

  public static final int _ACTIVE = 0;
  public static final PerformanceIRPConstDefs.PerformanceMonitoringState ACTIVE = new PerformanceIRPConstDefs.PerformanceMonitoringState(_ACTIVE);
  public static final int _SUSPENDED = 1;
  public static final PerformanceIRPConstDefs.PerformanceMonitoringState SUSPENDED = new PerformanceIRPConstDefs.PerformanceMonitoringState(_SUSPENDED);

  public int value ()
  {
    return __value;
  }

  public static PerformanceIRPConstDefs.PerformanceMonitoringState from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected PerformanceMonitoringState (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class PerformanceMonitoringState
