package PerformanceIRPConstDefs;


/**
* PerformanceIRPConstDefs/Schedule.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PerformanceIRPConstDefs_F.idl
* Thursday, June 21, 2018 8:22:15 AM GMT+01:00
*/

public final class Schedule implements org.omg.CORBA.portable.IDLEntity
{
  public TimeBase.UtcT start_time = null;
  public TimeBase.UtcT end_time = null;
  public int repeated_intervals[] = null;

  public Schedule ()
  {
  } // ctor

  public Schedule (TimeBase.UtcT _start_time, TimeBase.UtcT _end_time, int[] _repeated_intervals)
  {
    start_time = _start_time;
    end_time = _end_time;
    repeated_intervals = _repeated_intervals;
  } // ctor

} // class Schedule
