package PerformanceIRPConstDefs;


/**
* PerformanceIRPConstDefs/SuspectFlag.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PerformanceIRPConstDefs_F.idl
* Thursday, June 21, 2018 8:22:15 AM GMT+01:00
*/

public class SuspectFlag implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static PerformanceIRPConstDefs.SuspectFlag[] __array = new PerformanceIRPConstDefs.SuspectFlag [__size];

  public static final int _FALSE_ = 0;
  public static final PerformanceIRPConstDefs.SuspectFlag FALSE_ = new PerformanceIRPConstDefs.SuspectFlag(_FALSE_);
  public static final int _TRUE_ = 1;
  public static final PerformanceIRPConstDefs.SuspectFlag TRUE_ = new PerformanceIRPConstDefs.SuspectFlag(_TRUE_);

  public int value ()
  {
    return __value;
  }

  public static PerformanceIRPConstDefs.SuspectFlag from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected SuspectFlag (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class SuspectFlag
