#!/bin/bash
#===================================================================================
#
# FILE: trigger.sh
#
# USAGE: sh trigger.sh <JOB_ID> <JOB_FILE> <LOGGING>
#
# DESCRIPTION: Triggers full sync on nodes parallely using ssh/openssl
#              <JOB_ID> : any string
#              <JOB_FILE> : .job file generated by running collector.sh
#              <LOGGING> : true/false - generates log file per node
#       
#This will spawn the script  actionrunner.sh per each node for ||le execution.
#
# NOTES: Make sure to run the script from enviroment where NE IP are pingable
#        like MSCM server 
#
# AUTHOR: ZPALSRI(srihari.palivela@tcs.com)
# VERSION: 1.0
# CREATED: 15.03.2018 
#
#===================================================================================

if [[ $# -ne 2 ]];then
    echo "Invalid number of parameters"
    echo " USAGE: sh trigger.sh  <TYPE> <NUM_NODES>"
    exit
fi

JOB_FILE="allNodes.job"
TYPE=$1
NUM_NODES=$2

FILE="request_object.ser"
rm -rf ${FILE}


#generate and delete prmnresponse file
sh generateRequestPrmn.sh 
sh generateResponsePrmn.sh 

sleep 10



SAR_LOG="sarLog.sar"
rm -f ${SAR_LOG}

  sar 1  > ${SAR_LOG} &
    child_pid=$!
    echo " child pid = $child_pid"


## Create request_object.ser - contains serialized list of ObservationClass objects
java SerializeClassList ${TYPE}

#----------------------------------------------------------------------
# Spawns action runner per NE by iterating over .job file
#----------------------------------------------------------------------
COUNT=0
PROCESSES=""
SPACE=" "
i=0
while read -r line 
do
    SIM=$(echo $line | cut -d" " -f3)
    NE=$(echo $line | cut -d" " -f1)
    NEIP=$(echo $line | cut -d" " -f2)
    echo $line
    java PMSubscriber -ORBInitialPort 56834 -ORBInitialHost ${NEIP} -sim ${SIM} -ne ${NE} ${TYPE}&
    PROCESSES=$PROCESSES$!$SPACE
	i=$((i+1))
	if [[ $i -ge $NUM_NODES ]];then
	break
	fi
 
done< $JOB_FILE

echo "Processesss "$PROCESSES
wait $PROCESSES





`kill -9 ${child_pid}`  

sleep 60

#generate prmn file
sh generateRequestPrmn.sh
sh generateResponsePrmn.sh

