package ConfigExtended;


/**
* ConfigExtended/SequenceChangeInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_ext_K.idl
* Tuesday, May 22, 2018 12:36:12 PM GMT+01:00
*/

public final class SequenceChangeInfo implements org.omg.CORBA.portable.IDLEntity
{
  public org.omg.CORBA.Any value = null;
  public ConfigExtended.SequenceElementChangeType type = null;

  public SequenceChangeInfo ()
  {
  } // ctor

  public SequenceChangeInfo (org.omg.CORBA.Any _value, ConfigExtended.SequenceElementChangeType _type)
  {
    value = _value;
    type = _type;
  } // ctor

} // class SequenceChangeInfo
