package PerformanceIRPSystem;


/**
* PerformanceIRPSystem/InvalidObservationObjectListException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PerformanceIRPSystem_F.idl
* Thursday, June 21, 2018 8:22:22 AM GMT+01:00
*/

public final class InvalidObservationObjectListException extends org.omg.CORBA.UserException
{
  public PerformanceIRPConstDefs.ObservationObject observation_object_list[] = null;

  public InvalidObservationObjectListException ()
  {
    super(InvalidObservationObjectListExceptionHelper.id());
  } // ctor

  public InvalidObservationObjectListException (PerformanceIRPConstDefs.ObservationObject[] _observation_object_list)
  {
    super(InvalidObservationObjectListExceptionHelper.id());
    observation_object_list = _observation_object_list;
  } // ctor


  public InvalidObservationObjectListException (String $reason, PerformanceIRPConstDefs.ObservationObject[] _observation_object_list)
  {
    super(InvalidObservationObjectListExceptionHelper.id() + "  " + $reason);
    observation_object_list = _observation_object_list;
  } // ctor

} // class InvalidObservationObjectListException
