package PerformanceIRPSystem;


/**
* PerformanceIRPSystem/InvalidPerformanceMonitoringTypeException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PerformanceIRPSystem_F.idl
* Thursday, June 21, 2018 8:22:22 AM GMT+01:00
*/

public final class InvalidPerformanceMonitoringTypeException extends org.omg.CORBA.UserException
{

  public InvalidPerformanceMonitoringTypeException ()
  {
    super(InvalidPerformanceMonitoringTypeExceptionHelper.id());
  } // ctor


  public InvalidPerformanceMonitoringTypeException (String $reason)
  {
    super(InvalidPerformanceMonitoringTypeExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidPerformanceMonitoringTypeException
