package PerformanceIRPSystem;


/**
* PerformanceIRPSystem/OverloadException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PerformanceIRPSystem_F.idl
* Thursday, June 21, 2018 8:22:23 AM GMT+01:00
*/


//This exception is only thrown in the case all PerformanceMonitoringIDs does not exist
public final class OverloadException extends org.omg.CORBA.UserException
{

  public OverloadException ()
  {
    super(OverloadExceptionHelper.id());
  } // ctor


  public OverloadException (String $reason)
  {
    super(OverloadExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class OverloadException
