package PerformanceIRPSystem;

/**
* PerformanceIRPSystem/OverloadExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PerformanceIRPSystem_F.idl
* Thursday, June 21, 2018 8:22:23 AM GMT+01:00
*/


//This exception is only thrown in the case all PerformanceMonitoringIDs does not exist
public final class OverloadExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public PerformanceIRPSystem.OverloadException value = null;

  public OverloadExceptionHolder ()
  {
  }

  public OverloadExceptionHolder (PerformanceIRPSystem.OverloadException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PerformanceIRPSystem.OverloadExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PerformanceIRPSystem.OverloadExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PerformanceIRPSystem.OverloadExceptionHelper.type ();
  }

}
