package PerformanceIRPSystem;


/**
* PerformanceIRPSystem/PerformanceIRPOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PerformanceIRPSystem_F.idl
* Thursday, June 21, 2018 8:22:23 AM GMT+01:00
*/


//## Subsystem: PerforIRP-1
public interface PerformanceIRPOperations extends PerformanceIRPOperationsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PerformanceIRPOperations
