package BasicConfig;


/**
* BasicConfig/AttrIterRef.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_K.idl
* Tuesday, May 22, 2018 12:36:12 PM GMT+01:00
*/

public final class AttrIterRef implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;

  public AttrIterRef ()
  {
  } // ctor

  public AttrIterRef (int _id)
  {
    id = _id;
  } // ctor

} // class AttrIterRef
