package BasicConfig;


/**
* BasicConfig/MOidpair.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_K.idl
* Tuesday, May 22, 2018 12:36:12 PM GMT+01:00
*/

public final class MOidpair implements org.omg.CORBA.portable.IDLEntity
{
  private BasicConfig.MORef ___ref;
  private CosNaming.NameComponent[] ___name;
  private BasicConfig.MOidpairKind __discriminator;
  private boolean __uninitialized = true;

  public MOidpair ()
  {
  }

  public BasicConfig.MOidpairKind discriminator ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    return __discriminator;
  }

  public BasicConfig.MORef ref ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyref (__discriminator);
    return ___ref;
  }

  public void ref (BasicConfig.MORef value)
  {
    __discriminator = BasicConfig.MOidpairKind.RefType;
    ___ref = value;
    __uninitialized = false;
  }

  public void ref (BasicConfig.MOidpairKind discriminator, BasicConfig.MORef value)
  {
    verifyref (discriminator);
    __discriminator = discriminator;
    ___ref = value;
    __uninitialized = false;
  }

  private void verifyref (BasicConfig.MOidpairKind discriminator)
  {
    if (discriminator != BasicConfig.MOidpairKind.RefType)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public CosNaming.NameComponent[] name ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyname (__discriminator);
    return ___name;
  }

  public void name (CosNaming.NameComponent[] value)
  {
    __discriminator = BasicConfig.MOidpairKind.DNType;
    ___name = value;
    __uninitialized = false;
  }

  public void name (BasicConfig.MOidpairKind discriminator, CosNaming.NameComponent[] value)
  {
    verifyname (discriminator);
    __discriminator = discriminator;
    ___name = value;
    __uninitialized = false;
  }

  private void verifyname (BasicConfig.MOidpairKind discriminator)
  {
    if (discriminator != BasicConfig.MOidpairKind.DNType)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

} // class MOidpair
