package BasicConfig;


/**
* BasicConfig/QOS_NONE.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_K.idl
* Tuesday, May 22, 2018 12:36:11 PM GMT+01:00
*/

public interface QOS_NONE
{
  public static final short value = (short)(0);
}
