package BasicConfig;

/**
* BasicConfig/SecurityViolationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_K.idl
* Tuesday, May 22, 2018 12:36:11 PM GMT+01:00
*/

public final class SecurityViolationHolder implements org.omg.CORBA.portable.Streamable
{
  public BasicConfig.SecurityViolation value = null;

  public SecurityViolationHolder ()
  {
  }

  public SecurityViolationHolder (BasicConfig.SecurityViolation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BasicConfig.SecurityViolationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BasicConfig.SecurityViolationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BasicConfig.SecurityViolationHelper.type ();
  }

}
