package BasicConfig;


/**
* BasicConfig/SessionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_K.idl
* Tuesday, May 22, 2018 12:36:12 PM GMT+01:00
*/


/**
   * Session interface
   */
public interface SessionOperations 
{
  String get_session_id ();
  void restart () throws BasicConfig.ProcessingFailure;
  void begin (int operationTimeout) throws BasicConfig.ProcessingFailure;
  void rollback () throws BasicConfig.TransactionFailure;
  void commit () throws BasicConfig.TransactionFailure;
  void end () throws BasicConfig.TransactionFailure;
} // interface SessionOperations
