package AlarmIRPSystem;


/**
* AlarmIRPSystem/AlarmIRPOperationsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AlarmIRPSystem_F.idl
* Wednesday, July 11, 2018 2:25:07 PM GMT+01:00
*/


/*
  This interface specifies all methods supported by System as
	specified in 3GPP AlarmIRP: CORBA Solution Set version 1:1.
  */
abstract public class AlarmIRPOperationsHelper
{
  private static String  _id = "IDL:3gppsa5.org/AlarmIRPSystem/AlarmIRPOperations:1.0";

  public static void insert (org.omg.CORBA.Any a, AlarmIRPSystem.AlarmIRPOperations that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AlarmIRPSystem.AlarmIRPOperations extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (AlarmIRPSystem.AlarmIRPOperationsHelper.id (), "AlarmIRPOperations");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AlarmIRPSystem.AlarmIRPOperations read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AlarmIRPOperationsStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AlarmIRPSystem.AlarmIRPOperations value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static AlarmIRPSystem.AlarmIRPOperations narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AlarmIRPSystem.AlarmIRPOperations)
      return (AlarmIRPSystem.AlarmIRPOperations)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AlarmIRPSystem._AlarmIRPOperationsStub stub = new AlarmIRPSystem._AlarmIRPOperationsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static AlarmIRPSystem.AlarmIRPOperations unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AlarmIRPSystem.AlarmIRPOperations)
      return (AlarmIRPSystem.AlarmIRPOperations)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AlarmIRPSystem._AlarmIRPOperationsStub stub = new AlarmIRPSystem._AlarmIRPOperationsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
