package AlarmIRPSystem;


/**
* AlarmIRPSystem/AlarmIRPOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AlarmIRPSystem_F.idl
* Wednesday, July 11, 2018 2:25:07 PM GMT+01:00
*/


/*
  This interface specifies all methods supported by System as
	specified in 3GPP AlarmIRP: CORBA Solution Set version 1:1.
  */
public interface AlarmIRPOperations extends AlarmIRPOperationsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AlarmIRPOperations
