package AlarmIRPSystem;


/**
* AlarmIRPSystem/AlarmInformationIterator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AlarmIRPSystem_F.idl
* Wednesday, July 11, 2018 2:25:06 PM GMT+01:00
*/


/**
    The AlarmInformationIterator is used to iterate through a set of Alarm
    Informations in Alarm List.  Method get_alarm_list contains it as 
     output parameter.
    IRPManager uses it to pace the return of Alarm Informations. IRPManager
     cannot use it to pace when IRPAgent should retrieve Alarm Informations
     from Alarm List.
    */
public interface AlarmInformationIterator extends AlarmInformationIteratorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AlarmInformationIterator
