package AlarmIRPSystem;


/**
* AlarmIRPSystem/NextAlarmInformations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AlarmIRPSystem_F.idl
* Wednesday, July 11, 2018 2:25:06 PM GMT+01:00
*/

public final class NextAlarmInformations extends org.omg.CORBA.UserException
{
  public String reason = null;

  public NextAlarmInformations ()
  {
    super(NextAlarmInformationsHelper.id());
  } // ctor

  public NextAlarmInformations (String _reason)
  {
    super(NextAlarmInformationsHelper.id());
    reason = _reason;
  } // ctor


  public NextAlarmInformations (String $reason, String _reason)
  {
    super(NextAlarmInformationsHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class NextAlarmInformations
