package CosEventChannelAdmin;


/**
* CosEventChannelAdmin/ProxyPushSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosEventChannelAdmin.idl
* Wednesday, July 11, 2018 2:25:08 PM GMT+01:00
*/

public interface ProxyPushSupplier extends ProxyPushSupplierOperations, CosEventComm.PushSupplier, org.omg.CORBA.portable.IDLEntity 
{
} // interface ProxyPushSupplier
