package CosEventChannelAdmin;


/**
* CosEventChannelAdmin/SupplierAdmin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosEventChannelAdmin.idl
* Wednesday, July 11, 2018 2:25:08 PM GMT+01:00
*/

public interface SupplierAdmin extends SupplierAdminOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SupplierAdmin
