package CosEventComm;


/**
* CosEventComm/PullConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosEventComm.idl
* Wednesday, July 11, 2018 2:25:08 PM GMT+01:00
*/

public interface PullConsumerOperations 
{
  void disconnect_pull_consumer ();
} // interface PullConsumerOperations
