package TimeBase;

/**
* TimeBase/IntervalTHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TimeBase.idl
* Thursday, June 21, 2018 8:21:01 AM GMT+01:00
*/

public final class IntervalTHolder implements org.omg.CORBA.portable.Streamable
{
  public TimeBase.IntervalT value = null;

  public IntervalTHolder ()
  {
  }

  public IntervalTHolder (TimeBase.IntervalT initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TimeBase.IntervalTHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TimeBase.IntervalTHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TimeBase.IntervalTHelper.type ();
  }

}
