package CosNotifyComm;


/**
* CosNotifyComm/NotifySubscribe.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, July 11, 2018 2:25:10 PM GMT+01:00
*/


// NotifyPublish
public interface NotifySubscribe extends NotifySubscribeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface NotifySubscribe
