package CosNotifyComm;


/**
* CosNotifyComm/PushSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, July 11, 2018 2:25:10 PM GMT+01:00
*/


// PullSupplier
public interface PushSupplier extends PushSupplierOperations, CosNotifyComm.NotifySubscribe, CosEventComm.PushSupplier
{
} // interface PushSupplier
