package CosNotifyComm;


/**
* CosNotifyComm/PushConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, July 11, 2018 2:25:10 PM GMT+01:00
*/


// NotifySubscribe
public interface PushConsumer extends PushConsumerOperations, CosNotifyComm.NotifyPublish, CosEventComm.PushConsumer
{
} // interface PushConsumer
