package CosNotifyComm;


/**
* CosNotifyComm/SequencePullSupplierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, July 11, 2018 2:25:10 PM GMT+01:00
*/


// SequencePullConsumer
public interface SequencePullSupplierOperations  extends CosNotifyComm.NotifySubscribeOperations
{
  CosNotification.StructuredEvent[] pull_structured_events (int max_number) throws CosEventComm.Disconnected;
  CosNotification.StructuredEvent[] try_pull_structured_events (int max_number, org.omg.CORBA.BooleanHolder has_event) throws CosEventComm.Disconnected;
  void disconnect_sequence_pull_supplier ();
} // interface SequencePullSupplierOperations
