package CosNotifyComm;


/**
* CosNotifyComm/StructuredPullSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, July 11, 2018 2:25:10 PM GMT+01:00
*/


// StructuredPullConsumer
public interface StructuredPullSupplier extends StructuredPullSupplierOperations, CosNotifyComm.NotifySubscribe, org.omg.CORBA.portable.IDLEntity 
{
} // interface StructuredPullSupplier
