package CosNotifyComm;


/**
* CosNotifyComm/StructuredPushSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, July 11, 2018 2:25:10 PM GMT+01:00
*/


// StructuredPullSupplier
public interface StructuredPushSupplier extends StructuredPushSupplierOperations, CosNotifyComm.NotifySubscribe, org.omg.CORBA.portable.IDLEntity 
{
} // interface StructuredPushSupplier
