package CosNotifyComm;


/**
* CosNotifyComm/StructuredPullConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, July 11, 2018 2:25:10 PM GMT+01:00
*/


// StructuredPushConsumer
public interface StructuredPullConsumerOperations  extends CosNotifyComm.NotifyPublishOperations
{
  void disconnect_structured_pull_consumer ();
} // interface StructuredPullConsumerOperations
