package ConfigExtended;


/**
* ConfigExtended/DNameHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_ext_K.idl
* Tuesday, May 22, 2018 12:36:12 PM GMT+01:00
*/

abstract public class DNameHelper
{
  private static String  _id = "IDL:ConfigExtended/DName:1.0";

  public static void insert (org.omg.CORBA.Any a, CosNaming.NameComponent[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CosNaming.NameComponent[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = CosNaming.NameComponentHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (CosNaming.NameHelper.id (), "Name", __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (ConfigExtended.DNameHelper.id (), "DName", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CosNaming.NameComponent[] read (org.omg.CORBA.portable.InputStream istream)
  {
    CosNaming.NameComponent value[] = null;
    value = CosNaming.NameHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CosNaming.NameComponent[] value)
  {
    CosNaming.NameHelper.write (ostream, value);
  }

}
