package ConfigExtended;


/**
* ConfigExtended/SequenceElementChangeType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_ext_K.idl
* Tuesday, May 22, 2018 12:36:12 PM GMT+01:00
*/


/**
    * enum for SequenceElementChangeType which holds information of
    * the change type (ADD/DELETE) 
    */
public class SequenceElementChangeType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static ConfigExtended.SequenceElementChangeType[] __array = new ConfigExtended.SequenceElementChangeType [__size];

  public static final int _ADD = 0;
  public static final ConfigExtended.SequenceElementChangeType ADD = new ConfigExtended.SequenceElementChangeType(_ADD);
  public static final int _DELETE = 1;
  public static final ConfigExtended.SequenceElementChangeType DELETE = new ConfigExtended.SequenceElementChangeType(_DELETE);

  public int value ()
  {
    return __value;
  }

  public static ConfigExtended.SequenceElementChangeType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected SequenceElementChangeType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class SequenceElementChangeType
