package ConfigExtended.NotificationProducerPackage;

/**
* ConfigExtended/NotificationProducerPackage/NotificationFilterExtHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_ext_K.idl
* Tuesday, May 22, 2018 12:36:12 PM GMT+01:00
*/

public final class NotificationFilterExtHolder implements org.omg.CORBA.portable.Streamable
{
  public ConfigExtended.NotificationProducerPackage.NotificationFilterExt value = null;

  public NotificationFilterExtHolder ()
  {
  }

  public NotificationFilterExtHolder (ConfigExtended.NotificationProducerPackage.NotificationFilterExt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ConfigExtended.NotificationProducerPackage.NotificationFilterExtHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ConfigExtended.NotificationProducerPackage.NotificationFilterExtHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ConfigExtended.NotificationProducerPackage.NotificationFilterExtHelper.type ();
  }

}
