package AlarmIRPConstDefs;


/**
* AlarmIRPConstDefs/AttributeSetTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AlarmIRPConstDefs_F.idl
* Wednesday, July 11, 2018 2:25:05 PM GMT+01:00
*/

public final class AttributeSetTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public AlarmIRPConstDefs.AttributeValueType value[] = null;

  public AttributeSetTypeHolder ()
  {
  }

  public AttributeSetTypeHolder (AlarmIRPConstDefs.AttributeValueType[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AlarmIRPConstDefs.AttributeSetTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AlarmIRPConstDefs.AttributeSetTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AlarmIRPConstDefs.AttributeSetTypeHelper.type ();
  }

}
