package AlarmIRPConstDefs;


/**
* AlarmIRPConstDefs/ET_ENVIRONMENTAL_ALARM.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AlarmIRPConstDefs_F.idl
* Wednesday, July 11, 2018 2:25:05 PM GMT+01:00
*/

public interface ET_ENVIRONMENTAL_ALARM
{
  public static final String value = "x3";
}
