package AlarmIRPConstDefs;


/**
* AlarmIRPConstDefs/NOTIFY_FM_NEW_ALARM.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AlarmIRPConstDefs_F.idl
* Wednesday, July 11, 2018 2:25:05 PM GMT+01:00
*/

public interface NOTIFY_FM_NEW_ALARM
{

  /*
    This block identifies IRP defined, and not ITU-T defined, event types
    used by this Alarm IRP version.
    */
  public static final String value = "x1";
}
