package AlarmIRPConstDefs;


/**
* AlarmIRPConstDefs/PC_BATTERY_BREAKDOWN.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AlarmIRPConstDefs_F.idl
* Wednesday, July 11, 2018 2:25:06 PM GMT+01:00
*/

public interface PC_BATTERY_BREAKDOWN
{
  public static final short value = (short)(504);
}
