package AlarmIRPConstDefs;


/**
* AlarmIRPConstDefs/PC_DATA_SET_OR_MODEM_ERROR.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AlarmIRPConstDefs_F.idl
* Wednesday, July 11, 2018 2:25:06 PM GMT+01:00
*/

public interface PC_DATA_SET_OR_MODEM_ERROR
{
  public static final short value = (short)(311);
}
