package AlarmIRPConstDefs;


/**
* AlarmIRPConstDefs/PC_DEGRADED_SIGNAL_M3100.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AlarmIRPConstDefs_F.idl
* Wednesday, July 11, 2018 2:25:05 PM GMT+01:00
*/

public interface PC_DEGRADED_SIGNAL_M3100
{
  public static final short value = (short)(3);
}
