package AlarmIRPConstDefs;


/**
* AlarmIRPConstDefs/PC_HEATING_OR_VENTILATION_OR_COOLING_SYSTEM_PROBLEM.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AlarmIRPConstDefs_F.idl
* Wednesday, July 11, 2018 2:25:06 PM GMT+01:00
*/

public interface PC_HEATING_OR_VENTILATION_OR_COOLING_SYSTEM_PROBLEM
{
  public static final short value = (short)(321);
}
