package AlarmIRPConstDefs;


/**
* AlarmIRPConstDefs/PC_MAINS_BREAKDOWN_WITH_BATTERY_BACKUP.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AlarmIRPConstDefs_F.idl
* Wednesday, July 11, 2018 2:25:06 PM GMT+01:00
*/

public interface PC_MAINS_BREAKDOWN_WITH_BATTERY_BACKUP
{
  public static final short value = (short)(520);
}
