package AlarmIRPConstDefs;


/**
* AlarmIRPConstDefs/PS_INDETERMINATE.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AlarmIRPConstDefs_F.idl
* Wednesday, July 11, 2018 2:25:05 PM GMT+01:00
*/

public interface PS_INDETERMINATE
{

  /*
    This block identifies the levels of severity.
    */
  public static final short value = (short)(1);
}
