package Config;


/**
* Config/Configuration.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_K.idl
* Tuesday, May 22, 2018 12:36:12 PM GMT+01:00
*/


/**
   * Configuration interface
   */
public interface Configuration extends ConfigurationOperations, BasicConfig.BasicConfiguration, org.omg.CORBA.portable.IDLEntity 
{
} // interface Configuration
