package BasicConfig;


/**
* BasicConfig/AlreadyDefined.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_G.idl
* Friday, June 1, 2018 12:05:47 PM GMT+01:00
*/

public final class AlreadyDefined extends org.omg.CORBA.UserException
{
  public String info = null;

  public AlreadyDefined ()
  {
    super(AlreadyDefinedHelper.id());
  } // ctor

  public AlreadyDefined (String _info)
  {
    super(AlreadyDefinedHelper.id());
    info = _info;
  } // ctor


  public AlreadyDefined (String $reason, String _info)
  {
    super(AlreadyDefinedHelper.id() + "  " + $reason);
    info = _info;
  } // ctor

} // class AlreadyDefined
