package BasicConfig;


/**
* BasicConfig/AttributeNameSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_G.idl
* Friday, June 1, 2018 12:05:47 PM GMT+01:00
*/

public final class AttributeNameSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public AttributeNameSeqHolder ()
  {
  }

  public AttributeNameSeqHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BasicConfig.AttributeNameSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BasicConfig.AttributeNameSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BasicConfig.AttributeNameSeqHelper.type ();
  }

}
