package BasicConfig;


/**
* BasicConfig/ManagedObject.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_G.idl
* Friday, June 1, 2018 12:05:47 PM GMT+01:00
*/


/**
   * Interface for fine grain solution
   */
public interface ManagedObject extends ManagedObjectOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ManagedObject
