package BasicConfig;


/**
* BasicConfig/MOInfoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_G.idl
* Friday, June 1, 2018 12:05:47 PM GMT+01:00
*/

abstract public class MOInfoHelper
{
  private static String  _id = "IDL:BasicConfig/MOInfo/MOInfo:1.0";

  public static void insert (org.omg.CORBA.Any a, BasicConfig.MOInfo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BasicConfig.MOInfo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [7];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = BasicConfig.MORefHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "ref",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (BasicConfig.MOTypeHelper.id (), "MOType", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "type",
            _tcOf_members0,
            null);
          _tcOf_members0 = CosNaming.NameComponentHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (CosNaming.NameHelper.id (), "Name", _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (BasicConfig.DNameHelper.id (), "DName", _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "localDN",
            _tcOf_members0,
            null);
          _tcOf_members0 = CosNaming.NameComponentHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (CosNaming.NameHelper.id (), "Name", _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (BasicConfig.DNameHelper.id (), "DName", _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "fullDN",
            _tcOf_members0,
            null);
          _tcOf_members0 = BasicConfig.PlanningStateTypeHelper.type ();
          _members0[4] = new org.omg.CORBA.StructMember (
            "planningState",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (BasicConfig.MIBNameHelper.id (), "MIBName", _tcOf_members0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "mib",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulonglong);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (TimeBase.TimeTHelper.id (), "TimeT", _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (BasicConfig.TimeTHelper.id (), "TimeT", _tcOf_members0);
          _members0[6] = new org.omg.CORBA.StructMember (
            "created",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (BasicConfig.MOInfoHelper.id (), "MOInfo", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BasicConfig.MOInfo read (org.omg.CORBA.portable.InputStream istream)
  {
    BasicConfig.MOInfo value = new BasicConfig.MOInfo ();
    value.ref = BasicConfig.MORefHelper.read (istream);
    value.type = istream.read_string ();
    value.localDN = CosNaming.NameHelper.read (istream);
    value.fullDN = CosNaming.NameHelper.read (istream);
    value.planningState = BasicConfig.PlanningStateTypeHelper.read (istream);
    value.mib = istream.read_string ();
    value.created = istream.read_ulonglong ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BasicConfig.MOInfo value)
  {
    BasicConfig.MORefHelper.write (ostream, value.ref);
    ostream.write_string (value.type);
    CosNaming.NameHelper.write (ostream, value.localDN);
    CosNaming.NameHelper.write (ostream, value.fullDN);
    BasicConfig.PlanningStateTypeHelper.write (ostream, value.planningState);
    ostream.write_string (value.mib);
    ostream.write_ulonglong (value.created);
  }

}
