package BasicConfig;


/**
* BasicConfig/ProcessingFailure.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_G.idl
* Friday, June 1, 2018 12:05:47 PM GMT+01:00
*/

public final class ProcessingFailure extends org.omg.CORBA.UserException
{
  public String reason = null;

  public ProcessingFailure ()
  {
    super(ProcessingFailureHelper.id());
  } // ctor

  public ProcessingFailure (String _reason)
  {
    super(ProcessingFailureHelper.id());
    reason = _reason;
  } // ctor


  public ProcessingFailure (String $reason, String _reason)
  {
    super(ProcessingFailureHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class ProcessingFailure
