package BasicConfig;


/**
* BasicConfig/TopologyChangedInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_G.idl
* Friday, June 1, 2018 12:05:47 PM GMT+01:00
*/

public final class TopologyChangedInfo implements org.omg.CORBA.portable.IDLEntity
{
  public BasicConfig.DNinfo affectedMOs[] = null;
  public BasicConfig.RelInfo affectedRels[] = null;

  public TopologyChangedInfo ()
  {
  } // ctor

  public TopologyChangedInfo (BasicConfig.DNinfo[] _affectedMOs, BasicConfig.RelInfo[] _affectedRels)
  {
    affectedMOs = _affectedMOs;
    affectedRels = _affectedRels;
  } // ctor

} // class TopologyChangedInfo
