package Config;

/**
* Config/ConfigurationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_K.idl
* Tuesday, May 22, 2018 12:36:12 PM GMT+01:00
*/


/**
   * Configuration interface
   */
public final class ConfigurationHolder implements org.omg.CORBA.portable.Streamable
{
  public Config.Configuration value = null;

  public ConfigurationHolder ()
  {
  }

  public ConfigurationHolder (Config.Configuration initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Config.ConfigurationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Config.ConfigurationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Config.ConfigurationHelper.type ();
  }

}
