package ManagedGenericIRPConstDefs;


/**
* ManagedGenericIRPConstDefs/LongTypeOpt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ManagedGenericIRPConstDefs_E.idl
* Tuesday, July 10, 2018 8:45:23 AM GMT+01:00
*/

public final class LongTypeOpt implements org.omg.CORBA.portable.IDLEntity
{
  private int ___value;
  private boolean __discriminator;
  private boolean __uninitialized = true;

  public LongTypeOpt ()
  {
  }

  public boolean discriminator ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    return __discriminator;
  }

  public int value ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyvalue (__discriminator);
    return ___value;
  }

  public void value (int value)
  {
    __discriminator = true;
    ___value = value;
    __uninitialized = false;
  }

  public void value (boolean discriminator, int value)
  {
    verifyvalue (discriminator);
    __discriminator = discriminator;
    ___value = value;
    __uninitialized = false;
  }

  private void verifyvalue (boolean discriminator)
  {
    if (discriminator != true)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public void _default ()
  {
    __discriminator = false;
    __uninitialized = false;
  }

  public void _default (boolean discriminator)
  {
    verifyDefault( discriminator ) ;
    __discriminator = discriminator ;
    __uninitialized = false;
  }

  private void verifyDefault( boolean value )
  {
    int intValue;
    if (value == true){
        intValue = 1;
    }
    else {
        intValue = 0;
    }
    switch (intValue) {
      case 1:
        throw new org.omg.CORBA.BAD_OPERATION() ;

      default:
        return;
    }
  }

} // class LongTypeOpt
