#!/bin/bash
#===================================================================================
#
# FILE: trigger.sh
#
# USAGE: sh trigger.sh <JOB_ID> <JOB_FILE> <LOGGING>
#
# DESCRIPTION: Triggers full sync on nodes parallely using ssh/openssl
#              <JOB_ID> : any string
#              <JOB_FILE> : .job file generated by running collector.sh
#              <LOGGING> : true/false - generates log file per node
#       
#This will spawn the script  actionrunner.sh per each node for ||le execution.
#
# NOTES: Make sure to run the script from enviroment where NE IP are pingable
#        like MSCM server 
#
# AUTHOR: ZPALSRI(srihari.palivela@tcs.com)
# VERSION: 1.0
# CREATED: 15.03.2018 
#
#===================================================================================

JOB_FILE="allNodes.job"
NUM_NODES=$1
DEST=$2
DEST_PATH=$3
DUMMY=$4

if [[ $# -ne 4 ]];then
    echo "Invalid number of parameters"
    echo "Usage : sh $0 <NUM_NODES> <DEST_IP> <PATH_AT_DEST> <DUMMY>"
    exit 1
fi

i=0
SPACE=" "
DIRS=""
PM_DIRS=""
while IFS='' read -r line || [[ -n "$line" ]]; 
#while read -r line &&  [[ $i < ${NUM_NODES} ]];
do
        NE=$(echo $line | cut -d" " -f 1)
        DIRS=${DIRS}${SPACE}${NE}
	PM_DIRS=${PM_DIRS}${SPACE}${NE}"/PM"
        i=$((i+1))
        if [[ $i -ge $NUM_NODES ]];then
        break
        fi
done < $JOB_FILE
echo $DIRS
echo ${PM_DIRS}
sh createDir.sh ${DEST} ${DEST_PATH} "${DIRS}" "${PM_DIRS}"
echo "###sh createDir.sh ${DEST} ${DEST_PATH} ${DIRS} ${PM_DIRS}"


#----------------------------------------------------------------------
# Spawns action runner per NE by iterating over .job file
#----------------------------------------------------------------------

LOGGING=true
LOG="trigger.log"
# Clear log file
rm -f ${LOG}

PROCESSES=""
SPACE=" "
i=0

while IFS='' read -r line || [[ -n "$line" ]]; 
#while read -r line &&  [[ $i < ${NUM_NODES} ]];
do
	NE=$(echo $line | cut -d" " -f 1) 
	NE_IP=$(echo $line | cut -d" " -f 2)
   	sh subscribe.sh $NE ${NE_IP} $LOGGING ${DEST} "${DEST_PATH}/${NE}" ${DUMMY} &
   	PROCESSES=$PROCESSES$!$SPACE
	i=$((i+1))
	if [[ $i -ge $NUM_NODES ]];then
	break
	fi
	echo "LINE --------------> "$line
	echo "Spawned $i processes of $NUM_NODES"
done < $JOB_FILE

echo "Processesss "$PROCESSES
wait $PROCESSES

FAILED=`cat ${LOG} | grep "timedout" | wc -l`
if [[ $FAILED -ne 0 ]];then
	echo "#####################\n $FAILED nodes failed\n ######################\n"
else
	echo "#####################\n Subscription activated on all nodes\n ######################\n"
fi
