package CosNaming;


/**
* CosNaming/NamingContextPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNaming.idl
* Tuesday, May 22, 2018 12:36:11 PM GMT+01:00
*/

public abstract class NamingContextPOA extends org.omg.PortableServer.Servant
 implements CosNaming.NamingContextOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("bind", new java.lang.Integer (0));
    _methods.put ("rebind", new java.lang.Integer (1));
    _methods.put ("bind_context", new java.lang.Integer (2));
    _methods.put ("rebind_context", new java.lang.Integer (3));
    _methods.put ("resolve", new java.lang.Integer (4));
    _methods.put ("unbind", new java.lang.Integer (5));
    _methods.put ("new_context", new java.lang.Integer (6));
    _methods.put ("bind_new_context", new java.lang.Integer (7));
    _methods.put ("destroy", new java.lang.Integer (8));
    _methods.put ("list", new java.lang.Integer (9));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CosNaming/NamingContext/bind
       {
         try {
           CosNaming.NameComponent n[] = CosNaming.NameHelper.read (in);
           org.omg.CORBA.Object obj = org.omg.CORBA.ObjectHelper.read (in);
           this.bind (n, obj);
           out = $rh.createReply();
         } catch (CosNaming.NamingContextPackage.NotFound $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.NotFoundHelper.write (out, $ex);
         } catch (CosNaming.NamingContextPackage.CannotProceed $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.CannotProceedHelper.write (out, $ex);
         } catch (CosNaming.NamingContextPackage.InvalidName $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.InvalidNameHelper.write (out, $ex);
         } catch (CosNaming.NamingContextPackage.AlreadyBound $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.AlreadyBoundHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // CosNaming/NamingContext/rebind
       {
         try {
           CosNaming.NameComponent n[] = CosNaming.NameHelper.read (in);
           org.omg.CORBA.Object obj = org.omg.CORBA.ObjectHelper.read (in);
           this.rebind (n, obj);
           out = $rh.createReply();
         } catch (CosNaming.NamingContextPackage.NotFound $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.NotFoundHelper.write (out, $ex);
         } catch (CosNaming.NamingContextPackage.CannotProceed $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.CannotProceedHelper.write (out, $ex);
         } catch (CosNaming.NamingContextPackage.InvalidName $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.InvalidNameHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // CosNaming/NamingContext/bind_context
       {
         try {
           CosNaming.NameComponent n[] = CosNaming.NameHelper.read (in);
           CosNaming.NamingContext nc = CosNaming.NamingContextHelper.read (in);
           this.bind_context (n, nc);
           out = $rh.createReply();
         } catch (CosNaming.NamingContextPackage.NotFound $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.NotFoundHelper.write (out, $ex);
         } catch (CosNaming.NamingContextPackage.CannotProceed $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.CannotProceedHelper.write (out, $ex);
         } catch (CosNaming.NamingContextPackage.InvalidName $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.InvalidNameHelper.write (out, $ex);
         } catch (CosNaming.NamingContextPackage.AlreadyBound $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.AlreadyBoundHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // CosNaming/NamingContext/rebind_context
       {
         try {
           CosNaming.NameComponent n[] = CosNaming.NameHelper.read (in);
           CosNaming.NamingContext nc = CosNaming.NamingContextHelper.read (in);
           this.rebind_context (n, nc);
           out = $rh.createReply();
         } catch (CosNaming.NamingContextPackage.NotFound $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.NotFoundHelper.write (out, $ex);
         } catch (CosNaming.NamingContextPackage.CannotProceed $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.CannotProceedHelper.write (out, $ex);
         } catch (CosNaming.NamingContextPackage.InvalidName $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.InvalidNameHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // CosNaming/NamingContext/resolve
       {
         try {
           CosNaming.NameComponent n[] = CosNaming.NameHelper.read (in);
           org.omg.CORBA.Object $result = null;
           $result = this.resolve (n);
           out = $rh.createReply();
           org.omg.CORBA.ObjectHelper.write (out, $result);
         } catch (CosNaming.NamingContextPackage.NotFound $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.NotFoundHelper.write (out, $ex);
         } catch (CosNaming.NamingContextPackage.CannotProceed $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.CannotProceedHelper.write (out, $ex);
         } catch (CosNaming.NamingContextPackage.InvalidName $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.InvalidNameHelper.write (out, $ex);
         }
         break;
       }

       case 5:  // CosNaming/NamingContext/unbind
       {
         try {
           CosNaming.NameComponent n[] = CosNaming.NameHelper.read (in);
           this.unbind (n);
           out = $rh.createReply();
         } catch (CosNaming.NamingContextPackage.NotFound $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.NotFoundHelper.write (out, $ex);
         } catch (CosNaming.NamingContextPackage.CannotProceed $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.CannotProceedHelper.write (out, $ex);
         } catch (CosNaming.NamingContextPackage.InvalidName $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.InvalidNameHelper.write (out, $ex);
         }
         break;
       }

       case 6:  // CosNaming/NamingContext/new_context
       {
         CosNaming.NamingContext $result = null;
         $result = this.new_context ();
         out = $rh.createReply();
         CosNaming.NamingContextHelper.write (out, $result);
         break;
       }

       case 7:  // CosNaming/NamingContext/bind_new_context
       {
         try {
           CosNaming.NameComponent n[] = CosNaming.NameHelper.read (in);
           CosNaming.NamingContext $result = null;
           $result = this.bind_new_context (n);
           out = $rh.createReply();
           CosNaming.NamingContextHelper.write (out, $result);
         } catch (CosNaming.NamingContextPackage.NotFound $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.NotFoundHelper.write (out, $ex);
         } catch (CosNaming.NamingContextPackage.CannotProceed $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.CannotProceedHelper.write (out, $ex);
         } catch (CosNaming.NamingContextPackage.InvalidName $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.InvalidNameHelper.write (out, $ex);
         } catch (CosNaming.NamingContextPackage.AlreadyBound $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.AlreadyBoundHelper.write (out, $ex);
         }
         break;
       }

       case 8:  // CosNaming/NamingContext/destroy
       {
         try {
           this.destroy ();
           out = $rh.createReply();
         } catch (CosNaming.NamingContextPackage.NotEmpty $ex) {
           out = $rh.createExceptionReply ();
           CosNaming.NamingContextPackage.NotEmptyHelper.write (out, $ex);
         }
         break;
       }

       case 9:  // CosNaming/NamingContext/list
       {
         int how_many = in.read_ulong ();
         CosNaming.BindingListHolder bl = new CosNaming.BindingListHolder ();
         CosNaming.BindingIteratorHolder bi = new CosNaming.BindingIteratorHolder ();
         this.list (how_many, bl, bi);
         out = $rh.createReply();
         CosNaming.BindingListHelper.write (out, bl.value);
         CosNaming.BindingIteratorHelper.write (out, bi.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CosNaming/NamingContext:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public NamingContext _this() 
  {
    return NamingContextHelper.narrow(
    super._this_object());
  }

  public NamingContext _this(org.omg.CORBA.ORB orb) 
  {
    return NamingContextHelper.narrow(
    super._this_object(orb));
  }


} // class NamingContextPOA
