package ConfigExtended;


/**
* ConfigExtended/MIBChangeInfoSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_ext_K.idl
* Tuesday, May 22, 2018 12:36:12 PM GMT+01:00
*/

abstract public class MIBChangeInfoSeqHelper
{
  private static String  _id = "IDL:ConfigExtended/MIBChangeInfoSeq:1.0";

  public static void insert (org.omg.CORBA.Any a, ConfigExtended.MIBChangeInfo[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ConfigExtended.MIBChangeInfo[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = ConfigExtended.MIBChangeInfoHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (ConfigExtended.MIBChangeInfoSeqHelper.id (), "MIBChangeInfoSeq", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ConfigExtended.MIBChangeInfo[] read (org.omg.CORBA.portable.InputStream istream)
  {
    ConfigExtended.MIBChangeInfo value[] = null;
    int _len0 = istream.read_long ();
    value = new ConfigExtended.MIBChangeInfo[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = ConfigExtended.MIBChangeInfoHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ConfigExtended.MIBChangeInfo[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      ConfigExtended.MIBChangeInfoHelper.write (ostream, value[_i0]);
  }

}
