package ConfigExtended;


/**
* ConfigExtended/NotificationConsumerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_ext_K.idl
* Tuesday, May 22, 2018 12:36:12 PM GMT+01:00
*/

abstract public class NotificationConsumerHelper
{
  private static String  _id = "IDL:ConfigExtended/NotificationConsumer:1.0";

  public static void insert (org.omg.CORBA.Any a, ConfigExtended.NotificationConsumer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ConfigExtended.NotificationConsumer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ConfigExtended.NotificationConsumerHelper.id (), "NotificationConsumer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ConfigExtended.NotificationConsumer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_NotificationConsumerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ConfigExtended.NotificationConsumer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ConfigExtended.NotificationConsumer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ConfigExtended.NotificationConsumer)
      return (ConfigExtended.NotificationConsumer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ConfigExtended._NotificationConsumerStub stub = new ConfigExtended._NotificationConsumerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ConfigExtended.NotificationConsumer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ConfigExtended.NotificationConsumer)
      return (ConfigExtended.NotificationConsumer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ConfigExtended._NotificationConsumerStub stub = new ConfigExtended._NotificationConsumerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
