package CommonIRPConstDefs;


/**
* CommonIRPConstDefs/Signal.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CommonIRPConstDefs_E.idl
* Thursday, June 21, 2018 8:22:07 AM GMT+01:00
*/

public class Signal implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static CommonIRPConstDefs.Signal[] __array = new CommonIRPConstDefs.Signal [__size];

  public static final int _OK = 0;
  public static final CommonIRPConstDefs.Signal OK = new CommonIRPConstDefs.Signal(_OK);
  public static final int _Failure = 1;
  public static final CommonIRPConstDefs.Signal Failure = new CommonIRPConstDefs.Signal(_Failure);
  public static final int _PartialFailure = 2;
  public static final CommonIRPConstDefs.Signal PartialFailure = new CommonIRPConstDefs.Signal(_PartialFailure);

  public int value ()
  {
    return __value;
  }

  public static CommonIRPConstDefs.Signal from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Signal (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Signal
