package ConfigExtended.NotificationProducerPackage;

/**
* ConfigExtended/NotificationProducerPackage/MOTypeAndAttributesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_ext_K.idl
* Tuesday, May 22, 2018 12:36:12 PM GMT+01:00
*/

public final class MOTypeAndAttributesHolder implements org.omg.CORBA.portable.Streamable
{
  public ConfigExtended.NotificationProducerPackage.MOTypeAndAttributes value = null;

  public MOTypeAndAttributesHolder ()
  {
  }

  public MOTypeAndAttributesHolder (ConfigExtended.NotificationProducerPackage.MOTypeAndAttributes initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ConfigExtended.NotificationProducerPackage.MOTypeAndAttributesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ConfigExtended.NotificationProducerPackage.MOTypeAndAttributesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ConfigExtended.NotificationProducerPackage.MOTypeAndAttributesHelper.type ();
  }

}
