package PerformanceIRPSystem;


/**
* PerformanceIRPSystem/InvalidGranularityPeriodException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PerformanceIRPSystem_F.idl
* Thursday, June 21, 2018 8:22:22 AM GMT+01:00
*/

public final class InvalidGranularityPeriodException extends org.omg.CORBA.UserException
{

  public InvalidGranularityPeriodException ()
  {
    super(InvalidGranularityPeriodExceptionHelper.id());
  } // ctor


  public InvalidGranularityPeriodException (String $reason)
  {
    super(InvalidGranularityPeriodExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidGranularityPeriodException
