package PerformanceIRPSystem;


/**
* PerformanceIRPSystem/InvalidFilterException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PerformanceIRPSystem_F.idl
* Thursday, June 21, 2018 8:22:22 AM GMT+01:00
*/

public final class InvalidFilterException extends org.omg.CORBA.UserException
{

  public InvalidFilterException ()
  {
    super(InvalidFilterExceptionHelper.id());
  } // ctor


  public InvalidFilterException (String $reason)
  {
    super(InvalidFilterExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidFilterException
