package PerformanceIRPSystem;


/**
* PerformanceIRPSystem/OptionalParameterNotSupportedException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PerformanceIRPSystem_F.idl
* Thursday, June 21, 2018 8:22:23 AM GMT+01:00
*/

public final class OptionalParameterNotSupportedException extends org.omg.CORBA.UserException
{
  public String notSupportedParameters[] = null;

  public OptionalParameterNotSupportedException ()
  {
    super(OptionalParameterNotSupportedExceptionHelper.id());
  } // ctor

  public OptionalParameterNotSupportedException (String[] _notSupportedParameters)
  {
    super(OptionalParameterNotSupportedExceptionHelper.id());
    notSupportedParameters = _notSupportedParameters;
  } // ctor


  public OptionalParameterNotSupportedException (String $reason, String[] _notSupportedParameters)
  {
    super(OptionalParameterNotSupportedExceptionHelper.id() + "  " + $reason);
    notSupportedParameters = _notSupportedParameters;
  } // ctor

} // class OptionalParameterNotSupportedException
