package CelloNotificationIRPExtension;


/**
* CelloNotificationIRPExtension/NotificationIRPExtension.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CelloNotificationIRPExtension_F.idl
* Wednesday, July 11, 2018 2:25:07 PM GMT+01:00
*/


/*
   * This interface extends the Notification IRP with Cello 
   * specific support for filters on subscriptions.
   *
   */
public interface NotificationIRPExtension extends NotificationIRPExtensionOperations, NotificationIRPSystem.NotificationIRPOperations, org.omg.CORBA.portable.IDLEntity 
{
  public static final String NOTIFICATION_IRP_EXTENSION_VERSION_1_1 = "1nx1";
} // interface NotificationIRPExtension
