package se.ericsson.cello.LogAdmin;


/**
* se/ericsson/cello/LogAdmin/AvailabilityStatus.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LogAdmin_F.idl
* Wednesday, July 11, 2018 2:25:14 PM GMT+01:00
*/

public final class AvailabilityStatus implements org.omg.CORBA.portable.IDLEntity
{

  // when it is ful or available.
  public boolean log_full = false;

  public AvailabilityStatus ()
  {
  } // ctor

  public AvailabilityStatus (boolean _log_full)
  {
    log_full = _log_full;
  } // ctor

} // class AvailabilityStatus
