package se.ericsson.cello.LogAdmin;

/**
* se/ericsson/cello/LogAdmin/IteratorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LogAdmin_F.idl
* Wednesday, July 11, 2018 2:25:14 PM GMT+01:00
*/


//  from a query or retrieve operation.
public final class IteratorHolder implements org.omg.CORBA.portable.Streamable
{
  public se.ericsson.cello.LogAdmin.Iterator value = null;

  public IteratorHolder ()
  {
  }

  public IteratorHolder (se.ericsson.cello.LogAdmin.Iterator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = se.ericsson.cello.LogAdmin.IteratorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    se.ericsson.cello.LogAdmin.IteratorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return se.ericsson.cello.LogAdmin.IteratorHelper.type ();
  }

}
