package se.ericsson.cello.LogAdmin;


/**
* se/ericsson/cello/LogAdmin/LogAlreadyExists.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LogAdmin_F.idl
* Wednesday, July 11, 2018 2:25:14 PM GMT+01:00
*/

public final class LogAlreadyExists extends org.omg.CORBA.UserException
{

  public LogAlreadyExists ()
  {
    super(LogAlreadyExistsHelper.id());
  } // ctor


  public LogAlreadyExists (String $reason)
  {
    super(LogAlreadyExistsHelper.id() + "  " + $reason);
  } // ctor

} // class LogAlreadyExists
