package se.ericsson.cello.LogAdmin;

/**
* se/ericsson/cello/LogAdmin/OperationalStateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LogAdmin_F.idl
* Wednesday, July 11, 2018 2:25:14 PM GMT+01:00
*/


//  Defines the operational state of the log to performs its function.
public final class OperationalStateHolder implements org.omg.CORBA.portable.Streamable
{
  public se.ericsson.cello.LogAdmin.OperationalState value = null;

  public OperationalStateHolder ()
  {
  }

  public OperationalStateHolder (se.ericsson.cello.LogAdmin.OperationalState initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = se.ericsson.cello.LogAdmin.OperationalStateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    se.ericsson.cello.LogAdmin.OperationalStateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return se.ericsson.cello.LogAdmin.OperationalStateHelper.type ();
  }

}
