package se.ericsson.cello.LogAdmin;


/**
* se/ericsson/cello/LogAdmin/QoSType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LogAdmin_F.idl
* Wednesday, July 11, 2018 2:25:14 PM GMT+01:00
*/


//  Quality of Services supported by the log.
public class QoSType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static se.ericsson.cello.LogAdmin.QoSType[] __array = new se.ericsson.cello.LogAdmin.QoSType [__size];

  public static final int _NONE = 0;
  public static final se.ericsson.cello.LogAdmin.QoSType NONE = new se.ericsson.cello.LogAdmin.QoSType(_NONE);
  public static final int _RELIABILITY = 1;
  public static final se.ericsson.cello.LogAdmin.QoSType RELIABILITY = new se.ericsson.cello.LogAdmin.QoSType(_RELIABILITY);

  public int value ()
  {
    return __value;
  }

  public static se.ericsson.cello.LogAdmin.QoSType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected QoSType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class QoSType
