package se.ericsson.cello.LogAdmin;


/**
* se/ericsson/cello/LogAdmin/TimeT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LogAdmin_F.idl
* Wednesday, July 11, 2018 2:25:14 PM GMT+01:00
*/

public final class TimeT implements org.omg.CORBA.portable.IDLEntity
{
  public int year = (int)0;
  public int month = (int)0;
  public int day = (int)0;
  public int hour = (int)0;
  public int minute = (int)0;
  public int second = (int)0;

  public TimeT ()
  {
  } // ctor

  public TimeT (int _year, int _month, int _day, int _hour, int _minute, int _second)
  {
    year = _year;
    month = _month;
    day = _day;
    hour = _hour;
    minute = _minute;
    second = _second;
  } // ctor

} // class TimeT
