package CosNotifyFilter;


/**
* CosNotifyFilter/CallbackNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyFilter.idl
* Wednesday, July 11, 2018 2:25:11 PM GMT+01:00
*/

public final class CallbackNotFound extends org.omg.CORBA.UserException
{

  public CallbackNotFound ()
  {
    super(CallbackNotFoundHelper.id());
  } // ctor


  public CallbackNotFound (String $reason)
  {
    super(CallbackNotFoundHelper.id() + "  " + $reason);
  } // ctor

} // class CallbackNotFound
