package CosNotifyFilter;


/**
* CosNotifyFilter/FilterIDSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyFilter.idl
* Wednesday, July 11, 2018 2:25:11 PM GMT+01:00
*/

public final class FilterIDSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public FilterIDSeqHolder ()
  {
  }

  public FilterIDSeqHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyFilter.FilterIDSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyFilter.FilterIDSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyFilter.FilterIDSeqHelper.type ();
  }

}
