package CosNotifyFilter;

/**
* CosNotifyFilter/FilterFactoryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyFilter.idl
* Wednesday, July 11, 2018 2:25:11 PM GMT+01:00
*/


// MappingFilter
public final class FilterFactoryHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotifyFilter.FilterFactory value = null;

  public FilterFactoryHolder ()
  {
  }

  public FilterFactoryHolder (CosNotifyFilter.FilterFactory initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyFilter.FilterFactoryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyFilter.FilterFactoryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyFilter.FilterFactoryHelper.type ();
  }

}
