package CosNotifyFilter;


/**
* CosNotifyFilter/UnsupportedFilterableData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyFilter.idl
* Wednesday, July 11, 2018 2:25:10 PM GMT+01:00
*/

public final class UnsupportedFilterableData extends org.omg.CORBA.UserException
{

  public UnsupportedFilterableData ()
  {
    super(UnsupportedFilterableDataHelper.id());
  } // ctor


  public UnsupportedFilterableData (String $reason)
  {
    super(UnsupportedFilterableDataHelper.id() + "  " + $reason);
  } // ctor

} // class UnsupportedFilterableData
