package PmServiceExtended;

/**
* PmServiceExtended/PerformanceMonitoringExtendedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PerformanceMonitoringServiceExtended_F.idl
* Thursday, June 21, 2018 8:22:31 AM GMT+01:00
*/


/**
   * This interface is an extension of the Performance IRP 2:2 which is used for new additions to PMCI.
    *
    */
public final class PerformanceMonitoringExtendedHolder implements org.omg.CORBA.portable.Streamable
{
  public PmServiceExtended.PerformanceMonitoringExtended value = null;

  public PerformanceMonitoringExtendedHolder ()
  {
  }

  public PerformanceMonitoringExtendedHolder (PmServiceExtended.PerformanceMonitoringExtended initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PmServiceExtended.PerformanceMonitoringExtendedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PmServiceExtended.PerformanceMonitoringExtendedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PmServiceExtended.PerformanceMonitoringExtendedHelper.type ();
  }

}
