package NotificationIRPSystem;

/**
* NotificationIRPSystem/DetachExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NotificationIRPSystem_F.idl
* Wednesday, July 11, 2018 2:25:15 PM GMT+01:00
*/

public final class DetachExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public NotificationIRPSystem.DetachException value = null;

  public DetachExceptionHolder ()
  {
  }

  public DetachExceptionHolder (NotificationIRPSystem.DetachException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NotificationIRPSystem.DetachExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NotificationIRPSystem.DetachExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NotificationIRPSystem.DetachExceptionHelper.type ();
  }

}
