package NotificationIRPSystem;

/**
* NotificationIRPSystem/GetSubscriptionIdsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NotificationIRPSystem_F.idl
* Wednesday, July 11, 2018 2:25:15 PM GMT+01:00
*/

public final class GetSubscriptionIdsHolder implements org.omg.CORBA.portable.Streamable
{
  public NotificationIRPSystem.GetSubscriptionIds value = null;

  public GetSubscriptionIdsHolder ()
  {
  }

  public GetSubscriptionIdsHolder (NotificationIRPSystem.GetSubscriptionIds initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NotificationIRPSystem.GetSubscriptionIdsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NotificationIRPSystem.GetSubscriptionIdsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NotificationIRPSystem.GetSubscriptionIdsHelper.type ();
  }

}
