package NotificationIRPSystem;


/**
* NotificationIRPSystem/OperationNotSupported.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NotificationIRPSystem_F.idl
* Wednesday, July 11, 2018 2:25:15 PM GMT+01:00
*/

public final class OperationNotSupported extends org.omg.CORBA.UserException
{

  public OperationNotSupported ()
  {
    super(OperationNotSupportedHelper.id());
  } // ctor


  public OperationNotSupported (String $reason)
  {
    super(OperationNotSupportedHelper.id() + "  " + $reason);
  } // ctor

} // class OperationNotSupported
