#!/bin/bash
#===================================================================================
#
# FILE: trigger.sh
#
# USAGE: sh trigger.sh <JOB_ID> <JOB_FILE> <LOGGING>
#
# DESCRIPTION: Triggers full sync on nodes parallely using ssh/openssl
#              <JOB_ID> : any string
#              <JOB_FILE> : .job file generated by running collector.sh
#              <LOGGING> : true/false - generates log file per node
#       
#This will spawn the script  actionrunner.sh per each node for ||le execution.
#
# NOTES: Make sure to run the script from enviroment where NE IP are pingable
#        like MSCM server 
#
# AUTHOR: ZPALSRI(srihari.palivela@tcs.com)
# VERSION: 1.0
# CREATED: 15.03.2018 
#
#===================================================================================

if [[ $# -ne 1 ]];then
    echo "Invalid number of parameters"
    echo " USAGE: sh trigger.sh  <JOB_FILE> "
    exit
fi

JOB_FILE=$1


echo "Make sure to update paths in ERBSSynchronizer before running this script"
echo "Otherwise script may throw some errors "

echo "Have updated/verified paths in ERBSSynchronizer.java file : [Y/N]"
read var

if [[ "$var" = "Y" ]]; then
 echo "Good! Let's sync nodes"
else
 echo "Please update paths and re-run this script"
 exit 1
fi

RUN_ID=$(echo $JOB_FILE | cut -d"." -f1)


  sar 1  > ${RUN_ID}.sar &
    child_pid=$!
    echo " child pid = $child_pid"



#----------------------------------------------------------------------
# Spawns action runner per NE by iterating over .job file
#----------------------------------------------------------------------
declare -a PIDS
COUNT=0
while read -r line 
do
    SIM=$(echo $line | cut -d" " -f1)
    NE=$(echo $line | cut -d" " -f2)
    NEIP=$(echo $line | cut -d" " -f3)
    echo $line
    java ERBSSynchronizer -ORBInitialPort 56834 -ORBInitialHost ${NEIP} -sim ${SIM} -ne ${NE} &
    PIDS[${COUNT}]=$!    
    COUNT=`expr $COUNT + 1`
done< $JOB_FILE


for((i=0;i<COUNT;i++));
do
# Wait for all spawned process to complete
wait ${PIDS[${i}]}
done



`kill -9 ${child_pid}`  

