package ConfigExtended.NotificationProducerPackage;

/**
* ConfigExtended/NotificationProducerPackage/NotificationFilterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_ext_G.idl
* Friday, June 1, 2018 12:05:52 PM GMT+01:00
*/

public final class NotificationFilterHolder implements org.omg.CORBA.portable.Streamable
{
  public ConfigExtended.NotificationProducerPackage.NotificationFilter value = null;

  public NotificationFilterHolder ()
  {
  }

  public NotificationFilterHolder (ConfigExtended.NotificationProducerPackage.NotificationFilter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ConfigExtended.NotificationProducerPackage.NotificationFilterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ConfigExtended.NotificationProducerPackage.NotificationFilterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ConfigExtended.NotificationProducerPackage.NotificationFilterHelper.type ();
  }

}
