package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/SequenceProxyPullSupplierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyChannelAdmin.idl
* Wednesday, July 11, 2018 2:25:09 PM GMT+01:00
*/


// SequenceProxyPushConsumer
public interface SequenceProxyPullSupplierOperations 
{
} // interface SequenceProxyPullSupplierOperations
