package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/SequenceProxyPullSupplierPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyChannelAdmin.idl
* Wednesday, July 11, 2018 2:25:09 PM GMT+01:00
*/


// SequenceProxyPushConsumer
public abstract class SequenceProxyPullSupplierPOA extends org.omg.PortableServer.Servant
 implements CosNotifyChannelAdmin.SequenceProxyPullSupplierOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:omg.org/CosNotifyChannelAdmin/SequenceProxyPullSupplier:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public SequenceProxyPullSupplier _this() 
  {
    return SequenceProxyPullSupplierHelper.narrow(
    super._this_object());
  }

  public SequenceProxyPullSupplier _this(org.omg.CORBA.ORB orb) 
  {
    return SequenceProxyPullSupplierHelper.narrow(
    super._this_object(orb));
  }


} // class SequenceProxyPullSupplierPOA
