package CosNotifyChannelAdmin;

/**
* CosNotifyChannelAdmin/SequenceProxyPullSupplierHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyChannelAdmin.idl
* Wednesday, July 11, 2018 2:25:09 PM GMT+01:00
*/


// SequenceProxyPushConsumer
public final class SequenceProxyPullSupplierHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotifyChannelAdmin.SequenceProxyPullSupplier value = null;

  public SequenceProxyPullSupplierHolder ()
  {
  }

  public SequenceProxyPullSupplierHolder (CosNotifyChannelAdmin.SequenceProxyPullSupplier initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyChannelAdmin.SequenceProxyPullSupplierHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyChannelAdmin.SequenceProxyPullSupplierHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyChannelAdmin.SequenceProxyPullSupplierHelper.type ();
  }

}
