#!/bin/bash
#===================================================================================
#
# FILE: subscriber.sh
#
# USAGE: sh subscriber.sh <JOB_FILE> <TIME_OUT> <LOGGING>
#
# DESCRIPTION: Triggers full sync on nodes parallely using ssh/openssl
#              <JOB_FILE> : .job file generated by running collector.sh
#       
#This will spawn the script  subscriberclient.sh per each node for ||ly.
#
# NOTES: Make sure to run the script from enviroment where NE IP are pingable
#        like MSCM server 
#
# AUTHOR: ZPALSRI(srihari.palivela@tcs.com)
# VERSION: 1.0
# CREATED: 15.03.2018 
#
#===================================================================================

if [[ $# -ne 3 ]];then
    echo "Invalid number of parameters"
echo "  USAGE: sh subscriber.sh <JOB_FILE> <TIME_OUT> <LOGGING>"
    exit
fi

JOB_FILE=$1
TIMEOUT=$2
LOGGING=$3

#----------------------------------------------------------------------
# Spawns action runner per NE by iterating over .job file
#----------------------------------------------------------------------

while read -r line 
do
    PARAMS=$(echo $line | cut -d" " -f 1,2 ) 
	TLS=1
	echo prams $PARAMS    
sh subscriberclient.sh $PARAMS $TLS $TIMEOUT $LOGGING & 
done< $JOB_FILE

# Wait for all spawned process to complete
wait



