package ConfigExtended.NotificationProducerPackage;


/**
* ConfigExtended/NotificationProducerPackage/NotificationFilterHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_ext_K.idl
* Tuesday, May 22, 2018 12:36:12 PM GMT+01:00
*/

abstract public class NotificationFilterHelper
{
  private static String  _id = "IDL:ConfigExtended/NotificationProducer/NotificationFilter/NotificationFilter:1.0";

  public static void insert (org.omg.CORBA.Any a, ConfigExtended.NotificationProducerPackage.NotificationFilter that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ConfigExtended.NotificationProducerPackage.NotificationFilter extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (BasicConfig.MOTypeHelper.id (), "MOType", _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ConfigExtended.MOTypeHelper.id (), "MOType", _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ConfigExtended.NotificationProducerPackage.MOTypesHelper.id (), "MOTypes", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "types",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[1] = new org.omg.CORBA.StructMember (
            "topologyEvents",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[2] = new org.omg.CORBA.StructMember (
            "avcEvents",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ConfigExtended.FDNHelper.id (), "FDN", _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "baseMO",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (BasicConfig.ScopeHelper.id (), "Scope", _tcOf_members0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "scope",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ConfigExtended.NotificationProducerPackage.NotificationFilterHelper.id (), "NotificationFilter", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ConfigExtended.NotificationProducerPackage.NotificationFilter read (org.omg.CORBA.portable.InputStream istream)
  {
    ConfigExtended.NotificationProducerPackage.NotificationFilter value = new ConfigExtended.NotificationProducerPackage.NotificationFilter ();
    value.types = ConfigExtended.NotificationProducerPackage.MOTypesHelper.read (istream);
    value.topologyEvents = istream.read_boolean ();
    value.avcEvents = istream.read_boolean ();
    value.baseMO = istream.read_string ();
    value.scope = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ConfigExtended.NotificationProducerPackage.NotificationFilter value)
  {
    ConfigExtended.NotificationProducerPackage.MOTypesHelper.write (ostream, value.types);
    ostream.write_boolean (value.topologyEvents);
    ostream.write_boolean (value.avcEvents);
    ostream.write_string (value.baseMO);
    ostream.write_long (value.scope);
  }

}
