package BasicConfig;


/**
* BasicConfig/MGInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_K.idl
* Tuesday, May 22, 2018 12:36:12 PM GMT+01:00
*/

public final class MGInfo implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String name = null;
  public long created = (long)0;

  public MGInfo ()
  {
  } // ctor

  public MGInfo (int _id, String _name, long _created)
  {
    id = _id;
    name = _name;
    created = _created;
  } // ctor

} // class MGInfo
