package BasicConfig;

/**
* BasicConfig/TransactionFailureHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_K.idl
* Tuesday, May 22, 2018 12:36:11 PM GMT+01:00
*/

public final class TransactionFailureHolder implements org.omg.CORBA.portable.Streamable
{
  public BasicConfig.TransactionFailure value = null;

  public TransactionFailureHolder ()
  {
  }

  public TransactionFailureHolder (BasicConfig.TransactionFailure initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BasicConfig.TransactionFailureHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BasicConfig.TransactionFailureHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BasicConfig.TransactionFailureHelper.type ();
  }

}
