package BasicConfig;


/**
* BasicConfig/UndefinedValue.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_K.idl
* Tuesday, May 22, 2018 12:36:12 PM GMT+01:00
*/

public final class UndefinedValue implements org.omg.CORBA.portable.IDLEntity
{
  public int dummy = (int)0;

  public UndefinedValue ()
  {
  } // ctor

  public UndefinedValue (int _dummy)
  {
    dummy = _dummy;
  } // ctor

} // class UndefinedValue
