package NotificationIRPConstDefs;


/**
* NotificationIRPConstDefs/NotificationCategorySetHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NotificationIRPConstDefs_F.idl
* Wednesday, July 11, 2018 2:25:15 PM GMT+01:00
*/


/* 
  This is a string sequence identifying notification categories.
  A notification category is identified by the IRP name and its version.
  */
public final class NotificationCategorySetHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public NotificationCategorySetHolder ()
  {
  }

  public NotificationCategorySetHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NotificationIRPConstDefs.NotificationCategorySetHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NotificationIRPConstDefs.NotificationCategorySetHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NotificationIRPConstDefs.NotificationCategorySetHelper.type ();
  }

}
