package NotificationIRPConstDefs;


/**
* NotificationIRPConstDefs/NotifIDSetTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NotificationIRPConstDefs_F.idl
* Wednesday, July 11, 2018 2:25:15 PM GMT+01:00
*/

public final class NotifIDSetTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public NotifIDSetTypeHolder ()
  {
  }

  public NotifIDSetTypeHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NotificationIRPConstDefs.NotifIDSetTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NotificationIRPConstDefs.NotifIDSetTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NotificationIRPConstDefs.NotifIDSetTypeHelper.type ();
  }

}
