package NotificationIRPConstDefs;


/**
* NotificationIRPConstDefs/NV_ACK_TIME.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NotificationIRPConstDefs_F.idl
* Wednesday, July 11, 2018 2:25:15 PM GMT+01:00
*/

public interface NV_ACK_TIME
{
  public static final String value = "m";
}
