package NotificationIRPConstDefs;


/**
* NotificationIRPConstDefs/NV_NOTIFICATION_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NotificationIRPConstDefs_F.idl
* Wednesday, July 11, 2018 2:25:15 PM GMT+01:00
*/

public interface NV_NOTIFICATION_ID
{

  /*
    This block encapsulates string used in the name of the Name Value
    pair of the structured event.
    */
  public static final String value = "a";
}
