package NotificationIRPConstDefs;


/**
* NotificationIRPConstDefs/SubscriptionIdSetHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NotificationIRPConstDefs_F.idl
* Wednesday, July 11, 2018 2:25:15 PM GMT+01:00
*/

public final class SubscriptionIdSetHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public SubscriptionIdSetHolder ()
  {
  }

  public SubscriptionIdSetHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NotificationIRPConstDefs.SubscriptionIdSetHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NotificationIRPConstDefs.SubscriptionIdSetHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NotificationIRPConstDefs.SubscriptionIdSetHelper.type ();
  }

}
