package ManagedGenericIRPSystem;


/**
* ManagedGenericIRPSystem/InvalidParameter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ManagedGenericIRPSystem_NMS_C.idl
* Wednesday, July 11, 2018 2:25:14 PM GMT+01:00
*/


/*
   Exception thrown when an invalid parameter value is passed.
   The parameter shall be the actual parameter name.
   */
public final class InvalidParameter extends org.omg.CORBA.UserException
{
  public String parameter = null;

  public InvalidParameter ()
  {
    super(InvalidParameterHelper.id());
  } // ctor

  public InvalidParameter (String _parameter)
  {
    super(InvalidParameterHelper.id());
    parameter = _parameter;
  } // ctor


  public InvalidParameter (String $reason, String _parameter)
  {
    super(InvalidParameterHelper.id() + "  " + $reason);
    parameter = _parameter;
  } // ctor

} // class InvalidParameter
