package ManagedGenericIRPSystem;


/**
* ManagedGenericIRPSystem/OperationNotSupported.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ManagedGenericIRPSystem_NMS_C.idl
* Wednesday, July 11, 2018 2:25:14 PM GMT+01:00
*/


/*
   Exception thrown when an unsupported optional method is called.
   */
public final class OperationNotSupported extends org.omg.CORBA.UserException
{

  public OperationNotSupported ()
  {
    super(OperationNotSupportedHelper.id());
  } // ctor


  public OperationNotSupported (String $reason)
  {
    super(OperationNotSupportedHelper.id() + "  " + $reason);
  } // ctor

} // class OperationNotSupported
