from basic_network import USER_KEYS as USER, NODE_KEYS as NODE, TIME_KEYS as TIME, NODE_TYPES
#from profile_cmds import (CPP_AVC_BURST_MO_TYPE_SETTINGS, CREATE_DELETE_NOTIFICATION_INFO)


SCHEDULED_DAYS, SCHEDULE_SLEEP, SCHEDULED_TIMES_STRINGS = TIME
NUM_USERS, USER_ROLES = USER
NUM_NODES, SUPPORTED_NODE_TYPES, TOTAL_NODES, EXCLUDE_NODES_FROM, NODE_FILTER = NODE

ERBS, RADIONODE, SGSN, RNC, RBS, MGW, MLTN, SPITFIRE, ROUTER_6672, CISCO, SIU02, TCU02, TCU04, FRONTHAUL_6080, LH, MSRBS_V1, EPG, RadioTNode, SAPC, MTAS, MINILINK_6352, BSC, MSC_DB_BSP, MSC_BC_BSP, MSC_BC_IS = NODE_TYPES

fifteen_k_network = {
    "fifteen_k_network": {
        "amos": {},
        "aid": {
            'AID_02': {NUM_NODES: {ERBS: -1, RADIONODE: -1}, 'NUM_PROFILES': 2, 'FREQUENCY': 6, NUM_USERS: 1,
                       NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}}, USER_ROLES: ['AutoId_Administrator']}
        },
        "ap": {},
        "apt": {},
        "asrl": {},
        "bur": {},
        "cc": {},
        "cellcc": {},
        "cellmgt": {},
        "cli_mon": {},
        "cmcli": {},
        "cmevents_nbi": {},
        "cmexport": {},
        "cmimport": {
            'CMIMPORT_01': {'TIMES_PER_DAY': 24, TOTAL_NODES: 3, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE],
                            'BATCH_MO_SIZE': 10, USER_ROLES: ['Cmedit_Administrator'],
                            SCHEDULED_TIMES_STRINGS: ['03:00:01', '09:00:01', '17:00:01'],
                            'MO_VALUES': {'RetSubUnit': 1, 'AntennaSubunit': 1},
                            'MOS_ATTRS': {'RetSubUnit': ['userLabel'], 'AntennaSubunit': ['maxTotalTilt']},
                            'FILETYPE': '3GPP'},
            'CMIMPORT_02': {TOTAL_NODES: 1, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE],
                            'BATCH_MO_SIZE': 50, USER_ROLES: ['CM_REST_Administrator'],
                            'MO_VALUES': {'EUtranCellRelation': 12, 'UtranCellRelation': 12, 'GeranCellRelation': 6},
                            'MOS_ATTRS': {'UtranCellRelation': ['externalUtranCellFDDRef', 'UtranCellRelationId'],
                                          'EUtranCellRelation': ['EUtranCellRelationId', 'neighborCellRef'],
                                          'GeranCellRelation': ['GeranCellRelationId']},
                            SCHEDULED_TIMES_STRINGS: ['00:30:01', '01:30:01', '02:30:01', '03:30:01', '04:30:01',
                                                      '05:30:01', '06:30:01', '07:30:01', '08:30:01', '09:30:01'],
                            'FILETYPE': 'dynamic'},
            'CMIMPORT_03': {'MO_VALUES': {'TermPointToENB': 2},
                            'MOS_ATTRS': {'TermPointToENB': ['administrativeState']},
                            USER_ROLES: ['Cmedit_Administrator'], 'BATCH_MO_SIZE': 110,
                            TOTAL_NODES: 100, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE],
                            EXCLUDE_NODES_FROM: ['CMSYNC_01', 'CMSYNC_02', 'CMSYNC_03', 'CMSYNC_04', 'CMSYNC_05', 'CMSYNC_06'],
                            SCHEDULED_TIMES_STRINGS: ['08:45:01', '09:45:01', '10:45:01', '11:45:01', '12:45:01',
                                                      '13:45:01'], 'FILETYPE': '3GPP'},
            'CMIMPORT_04': {'MO_VALUES': {'EUtranCellRelation': 2},
                            'MOS_ATTRS': {'EUtranCellRelation': ['EUtranCellRelationId', 'neighborCellRef']},
                            USER_ROLES: ['Cmedit_Administrator'], TOTAL_NODES: 100, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE],
                            SCHEDULED_TIMES_STRINGS: ['12:50:01', '13:50:01', '14:50:01', '15:50:01', '16:50:01',
                                                      '17:50:01'],
                            'BATCH_MO_SIZE': 110, 'FILETYPE': 'dynamic'},
            'CMIMPORT_05': {'MO_VALUES': {'UtranFreqRelation': 5, 'EUtranFreqRelation': 5},
                            'MOS_ATTRS': {'UtranFreqRelation': ['userLabel'], 'EUtranFreqRelation': ['userLabel']},
                            USER_ROLES: ['CM_REST_Administrator'], SCHEDULED_TIMES_STRINGS: ['01:00:01', '10:00:01'],
                            'BATCH_MO_SIZE': 170, TOTAL_NODES: 500, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE],
                            'FILETYPE': '3GPP'},
            'CMIMPORT_07': {'CONFIG_NUM': 2, TOTAL_NODES: 1000, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE, RNC, RBS],
                            USER_ROLES: ['Cmedit_Administrator']},
            'CMIMPORT_09': {'FILETYPE': '3GPP', 'BATCH_MO_SIZE': 115,
                            USER_ROLES: ['Cmedit_Administrator'], TOTAL_NODES: 100, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE],
                            EXCLUDE_NODES_FROM: ['CMSYNC_01', 'CMSYNC_02', 'CMSYNC_03', 'CMSYNC_04', 'CMSYNC_05',
                                                 'CMSYNC_06', 'ENMCLI_02'],
                            SCHEDULED_TIMES_STRINGS: ['00:00:01', '07:00:01'],
                            'MO_VALUES': {'UtranCellRelation': 24, 'EUtranCellRelation': 24},
                            'MOS_ATTRS': {'UtranCellRelation': ['isHoAllowed'], 'EUtranCellRelation': ['isHoAllowed']}},
            'CMIMPORT_10': {SUPPORTED_NODE_TYPES: [ROUTER_6672], TOTAL_NODES: 316, 'BATCH_MO_SIZE': 100,
                            USER_ROLES: ['Cmedit_Administrator'], SCHEDULED_TIMES_STRINGS: ['02:10:00'],
                            'MO_VALUES': {'SwItem': 4}, 'MOS_ATTRS': {'SwItem': ['userLabel']},
                            'FILETYPE': 'dynamic'},
            'CMIMPORT_11': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE],
                            TOTAL_NODES: 1000, USER_ROLES: ['CM_REST_Administrator'],
                            'MO_VALUES': {'EUtranCellRelation': 12}, 'BATCH_MO_SIZE': 170,
                            SCHEDULED_TIMES_STRINGS: ['04:50:00'], 'FILETYPE': '3GPP'},
            'CMIMPORT_15': {USER_ROLES: ['CM_REST_Administrator'], NUM_USERS: 20, SCHEDULED_TIMES_STRINGS: ['09:00:01']}
        },
        "cmsync": {
            'CMSYNC_01': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], TOTAL_NODES: 10,
                          NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                          'NOTIFICATIONS_PER_SEC': 5, 'NOTIFICATION_INFO': 'CREATE_DELETE_NOTIFICATION_INFO'},
            'CMSYNC_02': {NUM_NODES: {ERBS: -1, RADIONODE: 11}, TOTAL_NODES: 47,
                          NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                          SCHEDULE_SLEEP: 1800, 'BURST_DURATION': 1860,
                          EXCLUDE_NODES_FROM: ["CMIMPORT_09", "CMIMPORT_03", "TOP_01"],
                          'NOTIFICATIONS_PER_SEC': 90, 'NOTIFICATION_INFO': 'CPP_AVC_BURST_MO_TYPE_SETTINGS'},
            'CMSYNC_03': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], TOTAL_NODES: 6,
                          NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                          'NOTIFICATIONS_PER_SEC': 3, 'NOTIFICATION_INFO': 'CREATE_DELETE_NOTIFICATION_INFO'},
            'CMSYNC_04': {NUM_NODES: {ERBS: -1, RADIONODE: 6}, TOTAL_NODES: 28,
                          NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                          SCHEDULE_SLEEP: 900, 'BURST_DURATION': 300,
                          EXCLUDE_NODES_FROM: ["CMIMPORT_09", "CMIMPORT_03", "TOP_01"],
                          'NOTIFICATIONS_PER_SEC': 48, 'NOTIFICATION_INFO': 'CPP_AVC_BURST_MO_TYPE_SETTINGS'},
            'CMSYNC_05': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], TOTAL_NODES: 30,
                          NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                          'NOTIFICATIONS_PER_SEC': 12, 'NOTIFICATION_INFO': 'CREATE_DELETE_NOTIFICATION_INFO'},
            'CMSYNC_06': {NUM_NODES: {ERBS: -1, RADIONODE: 34}, TOTAL_NODES: 132,
                          NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                          SCHEDULE_SLEEP: 7200, 'BURST_DURATION': 120,
                          EXCLUDE_NODES_FROM: ["CMIMPORT_09", "CMIMPORT_03", "TOP_01"],
                          'NOTIFICATIONS_PER_SEC': 236, 'NOTIFICATION_INFO': 'CPP_AVC_BURST_MO_TYPE_SETTINGS'},
            'CMSYNC_09': {SCHEDULED_DAYS: ["TUESDAY"], NUM_NODES: {ERBS: 250}, 'BURST_RATE': 1000, 'DURATION': 10,
                          'MO_ATTRIBUTE': 'ueTraceFileSize', 'BURST_ID': '591',
                          'MO_PATH': "ManagedElement=1,ENodeBFunction=1,PmEventService=1",
                          "MO_VALUES": [1010, 1020, 1000], SCHEDULED_TIMES_STRINGS: ["05:00:00"],
                          EXCLUDE_NODES_FROM: ["TOP_01", "CMIMPORT_03", "CMIMPORT_05", "CMIMPORT_08", "CMIMPORT_09",
                                               "CELLMGT_01", "CELLMGT_02"]}
        },
        "doc": {},
        "ebsl": {},
        "ebsm": {},
        "em": {
            'EM_01': {SUPPORTED_NODE_TYPES: [RADIONODE], TOTAL_NODES: 30, NUM_USERS: 30,
                      NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}}, SCHEDULE_SLEEP: 60 * 30,
                      USER_ROLES: ['Element_Manager_Operator', 'OPERATOR']}
        },
        "enmcli": {
            'ENMCLI_01': {NUM_NODES: {ERBS: -1, RADIONODE: -1, RNC: -1, RBS: -1},
                          NUM_USERS: 1, USER_ROLES: ['Cmedit_Administrator', 'Network_Explorer_Administrator'],
                          SCHEDULE_SLEEP: 60 * 60},
            'ENMCLI_02': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], TOTAL_NODES: 47,
                          NUM_USERS: 47, NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                          USER_ROLES: ['Cmedit_Administrator', 'Network_Explorer_Administrator'],
                          SCHEDULE_SLEEP: 60 * 15, EXCLUDE_NODES_FROM: ["TOP_01", 'CMIMPORT_09']},
            'ENMCLI_05': {TOTAL_NODES: 1500, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], NUM_USERS: 1,
                          USER_ROLES: ['Cmedit_Administrator', 'Network_Explorer_Administrator']}
        },
        "esm": {},
        "fm": {
            'FM_01': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE, MGW, SGSN, ROUTER_6672, RNC, RBS, BSC, MSC_DB_BSP],
                      TOTAL_NODES: 17, 'BURST_RATE': 5.6, 'DURATION': 1860, SCHEDULE_SLEEP: 1800,
                      'ALARM_SIZE_DISTRIBUTION': [1000, 1000, 1000, 1000, 2000, 2000, 2000, 2000, 3000, 4000],
                      'ALARM_PROBLEM_DISTRIBUTION': [
                          ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                          ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                          ('TU Synch Reference Loss of Signal', 'major'),
                          ('TU Synch Reference Loss of Signal', 'major'),
                          ('TU Synch Reference Loss of Signal', 'major'), ('Link Failure', 'critical'),
                          ('Link Failure', 'critical'), ('Link Failure', 'critical'), ('', 'warning'),
                          ('', 'warning')]},
            'FM_02': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE, MGW, SGSN, ROUTER_6672, RNC, RBS, BSC, MSC_DB_BSP],
                      TOTAL_NODES: 225, 'BURST_RATE': 40, 'DURATION': 300, SCHEDULE_SLEEP: 900,
                      'ALARM_SIZE_DISTRIBUTION': [1000, 1000, 1000, 1000, 2000, 2000, 2000, 2000, 3000, 4000],
                      'ALARM_PROBLEM_DISTRIBUTION': [
                          ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                          ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                          ('TU Synch Reference Loss of Signal', 'major'),
                          ('TU Synch Reference Loss of Signal', 'major'),
                          ('TU Synch Reference Loss of Signal', 'major'), ('Link Failure', 'critical'),
                          ('Link Failure', 'critical'), ('Link Failure', 'critical'), ('', 'warning'),
                          ('', 'warning')]},
            'FM_03': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE, MGW, SGSN, ROUTER_6672, RNC, RBS, BSC, MSC_DB_BSP],
                      TOTAL_NODES: 1000, 'BURST_RATE': 200, 'DURATION': 240, SCHEDULE_SLEEP: 10800,
                      'ALARM_SIZE_DISTRIBUTION': [1000, 1000, 1000, 1000, 2000, 2000, 2000, 2000, 3000, 4000],
                      'ALARM_PROBLEM_DISTRIBUTION': [
                          ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                          ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                          ('TU Synch Reference Loss of Signal', 'major'),
                          ('TU Synch Reference Loss of Signal', 'major'),
                          ('TU Synch Reference Loss of Signal', 'major'), ('Link Failure', 'critical'),
                          ('Link Failure', 'critical'), ('Link Failure', 'critical'), ('', 'warning'),
                          ('', 'warning')]},
            'FM_08': {TOTAL_NODES: 500, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE, ROUTER_6672], NUM_USERS: 10, 'NUM_USERS_1': 7,
                      'NUM_USERS_2': 3, USER_ROLES: ["FM_Operator"], SCHEDULE_SLEEP: 60 * 15},
            'FM_09': {TOTAL_NODES: 500, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE, ROUTER_6672], NUM_USERS: 12,
                      USER_ROLES: ["FM_Operator"], SCHEDULE_SLEEP: 60 * 15},
            'FM_12': {NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], 'TIMEOUT_SUBSCRIPTION': 60 * 24,
                      'NUMBER_NBI_SUBSCRIPTIONS': 15, 'TIMEOUT': 2, TOTAL_NODES: 0,
                      'NBI_filters': ["LTE0", "LTE1", "LTE2", "LTE3", "LTE4"],
                      'CORBA_ENABLED': True},
            'FM_14': {TOTAL_NODES: 1, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], NUM_USERS: 2, USER_ROLES: ["FM_Administrator"],
                      SCHEDULED_TIMES_STRINGS: ["16:00:00"]},
            'FM_16': {'NUMBER_BNSI_CLIENTS': 5}
        },
        "fmx": {},
        "ha": {},
        "lcm": {},
        "logviewer": {},
        "netex": {},
        "network": {},
        "nhc": {
            'NHC_01': {SCHEDULE_SLEEP: 60 * 120, NUM_USERS: 1, USER_ROLES: ["Nhc_Operator"],
                       SUPPORTED_NODE_TYPES: [ERBS, MGW, RNC, RBS], TOTAL_NODES: 1000}
        },
        "nhm": {},
        "nodecli": {
            'NODECLI_01': {NUM_USERS: 30, USER_ROLES: ['NodeCLI_Administrator', 'OPERATOR'], TOTAL_NODES: 30,
                           SUPPORTED_NODE_TYPES: [ERBS, RADIONODE, MLTN]}
        },
        "nodesec": {},
        "nvs": {},
        "migration": {},
        "parmgt": {},
        "pm": {},
        "secui": {
            'SECUI_02': {'NUMBER_OF_USERS': 30, 'NUMBER_OF_ROLES': 5, SCHEDULE_SLEEP: 24 * 60 * 60}
        },
        "shm": {
            'SHM_04': {NUM_NODES: {ERBS: 960}, SCHEDULED_TIMES_STRINGS: ["11:00:00"], 'TIMEOUT': 1800,
                       SCHEDULED_DAYS: ['WEDNESDAY']},
            'SHM_06': {NUM_USERS: 10, TOTAL_NODES: 10, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE, MLTN],
                       SCHEDULE_SLEEP: 60 * 60, USER_ROLES: ['Shm_Administrator', 'Cmedit_Administrator'],
                       EXCLUDE_NODES_FROM: ['SHM_01', 'SHM_18', 'SHM_03'],
                       NODE_FILTER: {RADIONODE: {'managed_element_type': ["ENodeB"]}}},
            'SHM_07': {NUM_USERS: 20, NUM_NODES: {ERBS: -1, RADIONODE: -1}, SCHEDULE_SLEEP: 3000,
                       USER_ROLES: ['Shm_Administrator', 'Network_Explorer_Administrator']},
            'SHM_17': {NUM_NODES: {ERBS: 1000}, SCHEDULED_TIMES_STRINGS: ["20:00:00"], SCHEDULED_DAYS: ['FRIDAY'],
                       "DEFAULT": False},
            'SHM_22': {NUM_NODES: {RADIONODE: 1000}, SCHEDULED_TIMES_STRINGS: ["21:00:00"], SCHEDULED_DAYS: ['FRIDAY'],
                       "DEFAULT": True, NODE_FILTER: {RADIONODE: {'managed_element_type': ["ENodeB"]}}},
            'SHM_23': {NUM_NODES: {MLTN: 200}, SCHEDULED_TIMES_STRINGS: ["03:00:00"], SCHEDULED_DAYS: ['SUNDAY']},
            'SHM_24': {'NODES_PER_HOST': 125, NUM_NODES: {MLTN: 200}, SCHEDULED_TIMES_STRINGS: ["08:00:00"],
                       SCHEDULED_DAYS: ['SUNDAY'], 'MAX_NODES': 200},
        },
        "top": {}
    }
}
