from basic_network import USER_KEYS as USER, NODE_KEYS as NODE, TIME_KEYS as TIME, NODE_TYPES
#from profile_cmds import (ENMCLI_COMMANDS, CELLMGT_MO_ATTRIBUTE_DATA, CPP_AVC_BURST_MO_TYPE_SETTINGS,
#                          CREATE_DELETE_NOTIFICATION_INFO, ROUTER_6000_AVC_BURST_MO_TYPE_SETTINGS)

SCHEDULED_DAYS, SCHEDULE_SLEEP, SCHEDULED_TIMES_STRINGS = TIME
NUM_USERS, USER_ROLES = USER
NUM_NODES, SUPPORTED_NODE_TYPES, TOTAL_NODES, EXCLUDE_NODES_FROM, NODE_FILTER = NODE

ERBS, RADIONODE, SGSN, RNC, RBS, MGW, MLTN, SPITFIRE, ROUTER_6672, CISCO, SIU02, TCU02, TCU04, FRONTHAUL_6080, LH, MSRBS_V1, EPG, RadioTNode, SAPC, MTAS, MINILINK_6352, BSC, MSC_DB_BSP, MSC_BC_BSP, MSC_BC_IS = NODE_TYPES

AMOS_USER_ROLES = ['ADMINISTRATOR', 'Amos_Administrator', 'BscApplicationAdministrator', 'Bts_Application_Administrator',
                   'ENodeB_Application_Administrator', 'ENodeB_Application_SecurityAdministrator',
                   'ENodeB_Application_User', 'EricssonSupport', 'NodeB_Application_Administrator',
                   'NodeB_Application_User', 'RBS_Application_Operator', 'Support_Application_Administrator',
                   'SystemAdministrator', 'SystemReadOnly', 'SystemSecurityAdministrator', 'Amos_Operator']

forty_k_network = {
    "forty_k_network": {
        "amos": {
            'AMOS_01': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                        TOTAL_NODES: 80, NUM_USERS: 80, USER_ROLES: AMOS_USER_ROLES, 'MAX_AMOS_SESSIONS': 150},
            'AMOS_02': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                        TOTAL_NODES: 80, NUM_USERS: 80, USER_ROLES: AMOS_USER_ROLES, 'MAX_AMOS_SESSIONS': 150},
            'AMOS_03': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                        TOTAL_NODES: 62, NUM_USERS: 62, USER_ROLES: AMOS_USER_ROLES, 'MAX_AMOS_SESSIONS': 150},
            'AMOS_04': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                        TOTAL_NODES: 61, NUM_USERS: 61, USER_ROLES: AMOS_USER_ROLES, 'MAX_AMOS_SESSIONS': 150},
            'AMOS_05': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                        TOTAL_NODES: 32, NUM_USERS: 32, USER_ROLES: AMOS_USER_ROLES + ['Scripting_Operator'], 'MAX_AMOS_SESSIONS': 150},
            'AMOS_06': {},
            'AMOS_07': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                        TOTAL_NODES: 100, NUM_USERS: 1, USER_ROLES: AMOS_USER_ROLES + ['Scripting_Operator'], 'MAX_AMOS_SESSIONS': 150,
                        SCHEDULE_SLEEP: 60 * 60, 'NUM_PARALLEL': 24},
            'AMOS_08': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                        TOTAL_NODES: 30, NUM_USERS: 1, USER_ROLES: AMOS_USER_ROLES, 'MAX_AMOS_SESSIONS': 150},
            'AMOS_09': {SCHEDULE_SLEEP: 60 * 60 * 24},
            'AMOS_10': {}
        },
        "aid": {
            'AID_SETUP': {NUM_USERS: 1, USER_ROLES: ['ADMINISTRATOR']},
            'AID_01': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], TOTAL_NODES: 2500, NUM_USERS: 10,
                       USER_ROLES: ['AutoId_Administrator'], NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}}},
            'AID_02': {NUM_NODES: {ERBS: -1, RADIONODE: -1}, 'NUM_PROFILES': 4, 'FREQUENCY': 12, NUM_USERS: 1,
                       USER_ROLES: ['AutoId_Administrator'], NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}}},
            'AID_03': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], TOTAL_NODES: 2500, NUM_USERS: 1,
                       USER_ROLES: ['AutoId_Administrator'], NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}}},
            'AID_04': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], TOTAL_NODES: 2500, NUM_USERS: 1,
                       USER_ROLES: ['AutoId_Administrator'], NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}}}
        },
        "ap": {
            'AP_SETUP': {'PROJECT_ZIP': 'ap_sample_project.zip'},
            'AP_01': {NUM_NODES: {RADIONODE: 100}, NUM_USERS: 1, SCHEDULED_TIMES_STRINGS: ["10:00:00", "15:00:00"],
                      USER_ROLES: ['ADMINISTRATOR'], 'PROJECT_NAME': 'ap_01_workload',
                      NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}}},
            'AP_10': {NUM_USERS: 2, USER_ROLES: ['ADMINISTRATOR'], SCHEDULE_SLEEP: 60 * 60},
            'AP_11': {NUM_USERS: 2, USER_ROLES: ['ADMINISTRATOR'], SCHEDULE_SLEEP: 60 * 15},
            'AP_12': {NUM_USERS: 2, USER_ROLES: ['ADMINISTRATOR'], SCHEDULE_SLEEP: 60 * 20},
            'AP_13': {NUM_USERS: 2, USER_ROLES: ['ADMINISTRATOR'], SCHEDULE_SLEEP: 60 * 10},
            'AP_14': {NUM_USERS: 2, USER_ROLES: ['ADMINISTRATOR'], SCHEDULE_SLEEP: 60 * 5},
            'AP_15': {NUM_USERS: 2, USER_ROLES: ['ADMINISTRATOR'], SCHEDULE_SLEEP: 60 * 30},
            'AP_16': {NUM_USERS: 2, USER_ROLES: ['ADMINISTRATOR'], SCHEDULE_SLEEP: 60 * 2}
        },
        "apt": {
            'APT_01': {NUM_NODES: {ERBS: 1},
                       "DEFAULT_NODES": {'ERBS': ['LTE29ERBS00025'],
                                         'SGSN': ['CORE01SGSN001', 'CORE01SGSN002', 'CORE01SGSN003']}},
        },
        "asrl": {
            'ASRL_01': {NUM_NODES: {ERBS: -1, RADIONODE: -1},
                        NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                        'ROP_INTERVAL': 'FIFTEEN_MIN', 'NUM_EVENTS': 1.0, 'NUM_COUNTERS': 1.0,
                        USER_ROLES: ["ASR-L_Administrator"]},
            'ASRL_02': {NUM_USERS: 1, USER_ROLES: ["ASR-L_Administrator"]},
            'ASRL_03': {NUM_USERS: 1, USER_ROLES: ["ASR-L_Administrator"]},
            'ASRL_04': {NUM_USERS: 1, USER_ROLES: ["ASR-L_Administrator"]},
        },
        "bur": {
            'BUR_02': {}
        },
        "cc": {
            'CC_01': {SCHEDULED_TIMES_STRINGS: ["02:00:00"],
                      SCHEDULED_DAYS: ['MONDAY', 'WEDNESDAY', 'FRIDAY', 'SUNDAY']}
        },
        "cellcc": {
            'CELLCC_01': {},
            'CELLCC_02': {}
        },
        "cellmgt": {
            'CELLMGT_01': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], TOTAL_NODES: 100,
                           NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB', 'ENodeB|NodeB']}},
                           USER_ROLES: ["ADMINISTRATOR"], 'MO_TYPE': 'EUtranCellFDD',
                           'MO_ATTRIBUTE_DATA': "CELLMGT_MO_ATTRIBUTE_DATA", 'REQUIRED_NUMBER_OF_NODES': 1,
                           'REQUIRED_NUMBER_OF_CELLS_PER_NODE': 4},
            'CELLMGT_02': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], TOTAL_NODES: 100,
                           NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB', 'ENodeB|NodeB']}},
                           USER_ROLES: ["ADMINISTRATOR"], 'MO_TYPE': 'EUtranCellFDD',
                           'MO_ATTRIBUTE_DATA': "CELLMGT_MO_ATTRIBUTE_DATA", 'REQUIRED_NUMBER_OF_NODES': 16,
                           'REQUIRED_NUMBER_OF_CELLS_PER_NODE': 4},
            'CELLMGT_03': {},
            'CELLMGT_04': {},
            'CELLMGT_05': {},
            'CELLMGT_06': {SCHEDULE_SLEEP: 60 * 30},
            'CELLMGT_07': {SUPPORTED_NODE_TYPES: [RNC], TOTAL_NODES: 16, USER_ROLES: ["ADMINISTRATOR"],
                           'MO_TYPE': 'UtranCell', 'MO_ATTRIBUTE_DATA': "CELLMGT_MO_ATTRIBUTE_DATA",
                           'REQUIRED_NUMBER_OF_NODES': 16, 'REQUIRED_NUMBER_OF_CELLS_PER_NODE': 4},
            'CELLMGT_08': {USER_ROLES: ["ADMINISTRATOR"], SCHEDULE_SLEEP: 60 * 60 * 24},
            'CELLMGT_09': {USER_ROLES: ["CM_REST_Administrator"],
                           SUPPORTED_NODE_TYPES: [ERBS, RADIONODE],
                           NODE_FILTER: {'RadioNode': {'managed_element_type': ['ENodeB']}},
                           TOTAL_NODES: 2500, NUM_USERS: 5,
                           'THREAD_QUEUE_TIMEOUT': 60 * 5, 'UI_DISPLAY_LIMIT': 50, 'SCHEDULE_SLEEP': 60 * 60},
            'CELLMGT_10': {USER_ROLES: ["CM_REST_Administrator"],
                           SUPPORTED_NODE_TYPES: [ERBS, RADIONODE],
                           NODE_FILTER: {'RadioNode': {'managed_element_type': ['ENodeB']}},
                           'MO_TYPE': 'EUtranCellFDD', 'REQUIRED_NUMBER_OF_CELLS_PER_NODE': 12,
                           TOTAL_NODES: 200, 'REQUIRED_NUMBER_OF_NODES': 20, NUM_USERS: 20,
                           'THREAD_QUEUE_TIMEOUT': 60 * 5, SCHEDULE_SLEEP: 60 * 72},
        },
        "cli_mon": {
            'CLI_MON_01': {SCHEDULE_SLEEP: 60 * 30},
            'CLI_MON_02': {SCHEDULE_SLEEP: 24 * 60 * 60},
            'CLI_MON_03': {SCHEDULE_SLEEP: 60 * 60 * 2}
        },
        "cmcli": {
            'CMCLI_01': {},
            'CMCLI_02': {},
            'CMCLI_03': {},
            'CMCLI_04': {},
            'CMCLI_05': {}
        },
        "cmevents_nbi": {
            'CMEVENTS_NBI_01': {SCHEDULE_SLEEP: 60, NUM_USERS: 10, USER_ROLES: ["ADMINISTRATOR"],
                                'EVENT_LIMIT': 10000}
        },
        "cmexport": {
            'CMEXPORT_01': {SCHEDULED_TIMES_STRINGS: ["06:00:00", "22:00:00"],
                            NUM_NODES: {ERBS: -1, RADIONODE: -1, RNC: -1, RBS: -1},
                            'FILETYPE': '3GPP', 'NODE_REGEX': '*LTE*;*dg2*;*RNC*', NUM_USERS: 1,
                            USER_ROLES: ['Cmedit_Operator']},
            'CMEXPORT_02': {NUM_NODES: {}, 'FILETYPE': ['3GPP', 'dynamic'], 'NUMBER_OF_NETWORK_EXPORTS': 3,
                            'OPERATOR_ROLE': ["Cmedit_Operator"], 'ADMIN_ROLE': ["Cmedit_Administrator"],
                            'THREAD_QUEUE_TIMEOUT': 100 * 60, 'VALIDATION_TIMEOUT': 8227,
                            SCHEDULED_TIMES_STRINGS: ["14:45:00"], SCHEDULED_DAYS: ['MONDAY', 'WEDNESDAY']},
            'CMEXPORT_03': {NUM_NODES: {ERBS: -1, RADIONODE: -1, RNC: -1, RBS: -1}, 'FILETYPE': 'dynamic',
                            NUM_USERS: 20, 'NUMBER_OF_EXPORTS': 20, USER_ROLES: ['CM_REST_Administrator'],
                            SCHEDULED_TIMES_STRINGS: ["03:45:00", "08:45:00", "14:15:00", "21:15:00"],
                            'THREAD_QUEUE_TIMEOUT': 5400, 'MO_RATE_MIN': 15000, 'MO_RATE_MAX': 20000,
                            'AVERAGE_MOS_PER_NODE': 2800},
            'CMEXPORT_05': {NUM_NODES: {ERBS: -1, RADIONODE: -1, RNC: -1, RBS: -1}, 'FILETYPE': ['3GPP', 'dynamic'],
                            'NODE_REGEX': '*LTE*;*dg2*;*RNC*', NUM_USERS: 1,
                            SCHEDULED_TIMES_STRINGS: ["08:00:00", "12:00:00"],
                            'SON_FILE': "CMEXPORT_05_SON_userFilter_v1.txt", USER_ROLES: ['Cmedit_Operator']},
            'CMEXPORT_06': {},
            'CMEXPORT_07': {SUPPORTED_NODE_TYPES: [ERBS], TOTAL_NODES: 300,
                            SCHEDULED_TIMES_STRINGS: ["02:30:00", "05:30:00", "08:30:00", "11:30:00", "14:30:00",
                                                      "17:30:00", "20:30:00", "23:30:00"],
                            'FILETYPE': '3GPP', NUM_USERS: 1, USER_ROLES: ['Cmedit_Operator']},
            'CMEXPORT_08': {NUM_NODES: {ERBS: -1, RADIONODE: -1}, 'FILETYPE': 'dynamic',
                            SCHEDULED_TIMES_STRINGS: ["13:05:00"], 'NUMBER_OF_EXPORTS': 10,
                            'NUMBER_OF_CELLS': 3, NUM_USERS: 10, USER_ROLES: ['CM_REST_Administrator']},
            'CMEXPORT_11': {TOTAL_NODES: 50, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], 'FILETYPE': '3GPP',
                            'NUMBER_OF_EXPORTS': 150, SCHEDULED_TIMES_STRINGS: ["01:40:00", "05:40:00", "09:40:00",
                                                                                "13:40:00", "17:40:00", "21:40:00"],
                            NUM_USERS: 1, USER_ROLES: ['CM_REST_Administrator']},
            'CMEXPORT_12': {'NODE_REGEX': '*LTE*;*dg2*;*K3C*;*SGSN*;*RNC*',
                            NUM_NODES: {ERBS: -1, SGSN: -1, MGW: -1, RADIONODE: -1, RNC: -1, RBS: -1},
                            SCHEDULED_TIMES_STRINGS: ["18:00:00"], 'FILETYPE': 'dynamic',
                            'NODE_BATCH_SIZE': 500, NUM_USERS: 1, USER_ROLES: ['CM_REST_Administrator']},
            'CMEXPORT_13': {NUM_NODES: {MGW: -1, SGSN: -1}, 'FILETYPE': '3GPP',
                            SCHEDULED_TIMES_STRINGS: ["14:00:00"], NUM_USERS: 1, USER_ROLES: ['Cmedit_Operator']},
            'CMEXPORT_14': {SCHEDULED_TIMES_STRINGS: ["19:00:00"], NUM_NODES: {MLTN: -1, SPITFIRE: -1,
                                                                               ROUTER_6672: -1, CISCO: -1,
                                                                               SIU02: -1, TCU02: -1, TCU04: -1,
                                                                               FRONTHAUL_6080: -1, LH: -1},
                            'FILETYPE': '3GPP', 'NODE_REGEX': '*ML*;*SPFRER*;*ASR*;*TCU*;*JUNIPER*;*SIU*',
                            NUM_USERS: 1, USER_ROLES: ['Cmedit_Operator']},
            'CMEXPORT_15': {},
            'CMEXPORT_16': {NUM_NODES: {}, NUM_USERS: 1, SCHEDULED_TIMES_STRINGS: ["18:45:00"],
                            USER_ROLES: ['Cmedit_Operator', 'Shm_Administrator']},
            'CMEXPORT_17': {NUM_USERS: 1, USER_ROLES: ['Cmedit_Operator'], 'FILE_RETENTION_TIME': 30 * 60},
            'CMEXPORT_18': {},
            'CMEXPORT_19': {'ENIQ_SCRIPT': "sudo /opt/ericsson/ENM_ENIQ_Integration/eniq_enm_integration.py "
                                           "eniqcmexport",
                            'ENIQ_SCRIPT_FOR_CLOUD': "sudo /opt/ericsson/ENM_ENIQ_Integration/eniq_venm_integration.py "
                                                     "eniqcmexport",
                            'LITP_PLAN': ['/usr/bin/python /usr/bin/litp show_plan -a', 'Plan Status: Successful']},
            'CMEXPORT_20': {TOTAL_NODES: 50, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE],
                            NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                            'FILETYPE': 'dynamic', SCHEDULED_TIMES_STRINGS: ["04:15:00"], NUM_USERS: 1,
                            USER_ROLES: ['CM_REST_Administrator']}
        },
        "cmimport": {
            'CMIMPORT_01': {'TIMES_PER_DAY': 48, TOTAL_NODES: 3, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE],
                            'BATCH_MO_SIZE': 10, USER_ROLES: ['Cmedit_Administrator'],
                            SCHEDULED_TIMES_STRINGS: ['03:00:01', '09:00:01', '17:00:01'],
                            'MO_VALUES': {'RetSubUnit': 1, 'AntennaSubunit': 1}, 'FILETYPE': '3GPP',
                            'MOS_ATTRS': {'RetSubUnit': ['userLabel'], 'AntennaSubunit': ['maxTotalTilt']}},
            'CMIMPORT_02': {TOTAL_NODES: 1, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE],
                            'BATCH_MO_SIZE': 50, USER_ROLES: ['CM_REST_Administrator'],
                            'MO_VALUES': {'EUtranCellRelation': 12, 'UtranCellRelation': 12, 'GeranCellRelation': 6},
                            'MOS_ATTRS': {'UtranCellRelation': ['externalUtranCellFDDRef', 'UtranCellRelationId'],
                                          'EUtranCellRelation': ['EUtranCellRelationId', 'neighborCellRef'],
                                          'GeranCellRelation': ['GeranCellRelationId']},
                            SCHEDULED_TIMES_STRINGS: ['00:30:01', '01:30:01', '02:30:01', '03:30:01', '04:30:01',
                                                      '05:30:01', '06:30:01', '07:30:01', '08:30:01', '09:30:01',
                                                      '10:30:01', '11:30:01', '12:30:01', '13:30:01', '14:30:01',
                                                      '15:30:01', '16:30:01', '17:30:01', '18:30:01', '19:30:01',
                                                      '20:30:01', '21:30:01', '22:30:01', '23:30:01'],
                            'FILETYPE': 'dynamic'},
            'CMIMPORT_03': {'MO_VALUES': {'TermPointToENB': 2},
                            'MOS_ATTRS': {'TermPointToENB': ['administrativeState']},
                            USER_ROLES: ['Cmedit_Administrator'], 'BATCH_MO_SIZE': 110,
                            TOTAL_NODES: 100, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE],
                            EXCLUDE_NODES_FROM: ['CMSYNC_01', 'CMSYNC_02', 'CMSYNC_03', 'CMSYNC_04', 'CMSYNC_05',
                                                 'CMSYNC_06'],
                            SCHEDULED_TIMES_STRINGS: ['08:45:01', '09:45:01', '10:45:01', '11:45:01', '12:45:01',
                                                      '13:45:01', '14:45:01', '15:45:01', '16:45:01', '17:45:01',
                                                      '18:45:01', '19:45:01', '20:45:01', '21:45:01', '22:45:01',
                                                      '23:45:01'], 'FILETYPE': '3GPP'},
            'CMIMPORT_04': {'MO_VALUES': {'EUtranCellRelation': 2},
                            'MOS_ATTRS': {'EUtranCellRelation': ['EUtranCellRelationId', 'neighborCellRef']},
                            USER_ROLES: ['Cmedit_Administrator'], TOTAL_NODES: 100, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE],
                            SCHEDULED_TIMES_STRINGS: ['12:50:01', '13:50:01', '14:50:01', '15:50:01', '16:50:01',
                                                      '17:50:01', '18:50:01', '19:50:01', '20:50:01', '21:50:01',
                                                      '22:50:01', '23:50:01'],
                            'BATCH_MO_SIZE': 110, 'FILETYPE': 'dynamic'},
            'CMIMPORT_05': {'MO_VALUES': {'UtranFreqRelation': 5, 'EUtranFreqRelation': 5},
                            'MOS_ATTRS': {'UtranFreqRelation': ['userLabel'], 'EUtranFreqRelation': ['userLabel']},
                            USER_ROLES: ['CM_REST_Administrator'], 'FILETYPE': '3GPP',
                            SCHEDULED_TIMES_STRINGS: ['01:00:01', '10:00:01', '16:00:01', '23:00:01'],
                            'BATCH_MO_SIZE': 170, TOTAL_NODES: 500, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE]},
            'CMIMPORT_06': {},
            'CMIMPORT_07': {'CONFIG_NUM': 8, TOTAL_NODES: 1000, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE, RNC, RBS],
                            USER_ROLES: ['Cmedit_Administrator']},
            'CMIMPORT_08': {'MO_VALUES': {'UtranFreqRelation': 1, 'EUtranFreqRelation': 1},
                            'MOS_ATTRS': {'UtranFreqRelation': ['userLabel'], 'EUtranFreqRelation': ['userLabel']},
                            TOTAL_NODES: 50, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], 'BATCH_MO_SIZE': 50,
                            USER_ROLES: ['Cmedit_Administrator'],
                            SCHEDULED_TIMES_STRINGS: ['13:15:01', '15:15:01', '18:15:01', '21:15:01'], 'FILETYPE': 'dynamic'},
            'CMIMPORT_09': {'FILETYPE': '3GPP', 'BATCH_MO_SIZE': 115, USER_ROLES: ['Cmedit_Administrator'],
                            TOTAL_NODES: 100, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE],
                            EXCLUDE_NODES_FROM: ['CMSYNC_01', 'CMSYNC_02', 'CMSYNC_03', 'CMSYNC_04', 'CMSYNC_05',
                                                 'CMSYNC_06', 'ENMCLI_02'],
                            SCHEDULED_TIMES_STRINGS: ['00:00:01', '07:00:01', '11:00:01', '19:00:01'],
                            'MO_VALUES': {'UtranCellRelation': 24, 'EUtranCellRelation': 24},
                            'MOS_ATTRS': {'UtranCellRelation': ['isHoAllowed'], 'EUtranCellRelation': ['isHoAllowed']}},
            'CMIMPORT_10': {SUPPORTED_NODE_TYPES: [ROUTER_6672], TOTAL_NODES: 500, 'BATCH_MO_SIZE': 100,
                            USER_ROLES: ['Cmedit_Administrator'], SCHEDULED_TIMES_STRINGS: ['02:10:00'],
                            'MO_VALUES': {'SwItem': 4}, 'MOS_ATTRS': {'SwItem': ['userLabel']},
                            'FILETYPE': 'dynamic'},
            'CMIMPORT_11': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE],
                            TOTAL_NODES: 1000, USER_ROLES: ['CM_REST_Administrator'],
                            'MO_VALUES': {'EUtranCellRelation': 12}, 'BATCH_MO_SIZE': 170,
                            SCHEDULED_TIMES_STRINGS: ['04:50:00'], 'FILETYPE': '3GPP'},
            'CMIMPORT_12': {'FILETYPE': 'dynamic', 'BATCH_MO_SIZE': 50, USER_ROLES: ['CM_REST_Administrator'],
                            TOTAL_NODES: 50, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE, RBS],
                            SCHEDULED_TIMES_STRINGS: ['09:25:01', '10:25:01', '11:25:01', '12:25:01', '13:25:01', '14:25:01'],
                            'MO_VALUES': {'GeranCellRelation': 4},
                            'MOS_ATTRS': {'GeranCellRelation': ['isHoAllowed']}},
            'CMIMPORT_13': {'MO_VALUES': {'UtranCellRelation': 2}, 'MOS_ATTRS': {'UtranCellRelation': ['isRemoveAllowed']},
                            USER_ROLES: ['CM_REST_Administrator'], TOTAL_NODES: 10, SUPPORTED_NODE_TYPES: [RADIONODE, RBS],
                            SCHEDULED_TIMES_STRINGS: ['04:00:01', '12:00:01', '18:00:01', '21:00:01'],
                            'BATCH_MO_SIZE': 50, 'FILETYPE': '3GPP'},
            'CMIMPORT_14': {'MO_VALUES': {'EUtranCellRelation': 234, 'UtranCellRelation': 233, 'TermPointToENB': 233},
                            'MOS_ATTRS': {'EUtranCellRelation': ['EUtranCellRelationId', 'neighborCellRef'],
                                          'UtranCellRelation': ['utranCellRelationId', 'externalUtranCellFDDRef'],
                                          'TermPointToENB': ['TermPointToENBId']},
                            USER_ROLES: ['Cmedit_Administrator'], TOTAL_NODES: 1,
                            SUPPORTED_NODE_TYPES: [RADIONODE], 'BATCH_MO_SIZE': 100, 'FILETYPE': '3GPP',
                            NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                            SCHEDULED_TIMES_STRINGS: ['02:30:01', '04:30:01', '07:30:01', '09:50:01', '13:00:01',
                                                      '15:30:01', '17:30:01', '19:30:01', '21:30:01', '23:30:01']},
            'CMIMPORT_15': {USER_ROLES: ['CM_REST_Administrator'], NUM_USERS: 50, SCHEDULED_TIMES_STRINGS: ['09:00:01']},
            'CMIMPORT_16': {'FILETYPE': 'dynamic', 'BATCH_MO_SIZE': 150, USER_ROLES: ['CM_REST_Administrator'],
                            SUPPORTED_NODE_TYPES: [TCU02, SIU02], TOTAL_NODES: 1000,
                            SCHEDULED_TIMES_STRINGS: ['20:00:01'], SCHEDULED_DAYS: ["THURSDAY"],
                            'MO_VALUES': {'STN': 1}, 'MOS_ATTRS': {'STN': ['userLabel']}}
        },
        "cmsync": {
            'CMSYNC_01': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], TOTAL_NODES: 40,
                          NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                          'NOTIFICATIONS_PER_SEC': 20, 'NOTIFICATION_INFO': "CREATE_DELETE_NOTIFICATION_INFO"},
            'CMSYNC_02': {NUM_NODES: {ERBS: -1, RADIONODE: 49}, TOTAL_NODES: 190,
                          NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                          SCHEDULE_SLEEP: 1800, 'BURST_DURATION': 1860,
                          EXCLUDE_NODES_FROM: ["CMIMPORT_09", "CMIMPORT_03", "TOP_01"],
                          'NOTIFICATIONS_PER_SEC': 361, 'NOTIFICATION_INFO': "CPP_AVC_BURST_MO_TYPE_SETTINGS"},
            'CMSYNC_03': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], TOTAL_NODES: 20,
                          NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                          'NOTIFICATIONS_PER_SEC': 10, 'NOTIFICATION_INFO': "CREATE_DELETE_NOTIFICATION_INFO"},
            'CMSYNC_04': {NUM_NODES: {ERBS: -1, RADIONODE: 25}, TOTAL_NODES: 100,
                          NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                          SCHEDULE_SLEEP: 900, 'BURST_DURATION': 300,
                          EXCLUDE_NODES_FROM: ["CMIMPORT_09", "CMIMPORT_03", "TOP_01"],
                          'NOTIFICATIONS_PER_SEC': 190, 'NOTIFICATION_INFO': "CPP_AVC_BURST_MO_TYPE_SETTINGS"},
            'CMSYNC_05': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], TOTAL_NODES: 100,
                          NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                          'NOTIFICATIONS_PER_SEC': 48, 'NOTIFICATION_INFO': "CREATE_DELETE_NOTIFICATION_INFO"},
            'CMSYNC_06': {NUM_NODES: {ERBS: -1, RADIONODE: 125}, TOTAL_NODES: 500,
                          NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                          SCHEDULE_SLEEP: 7200, 'BURST_DURATION': 120,
                          EXCLUDE_NODES_FROM: ["CMIMPORT_09", "CMIMPORT_03", "TOP_01"],
                          'NOTIFICATIONS_PER_SEC': 950, 'NOTIFICATION_INFO': "CPP_AVC_BURST_MO_TYPE_SETTINGS"},
            'CMSYNC_07': {},
            'CMSYNC_08': {SCHEDULED_DAYS: ['MONDAY'], NUM_NODES: {ERBS: 20}, 'BURST_RATE': 20, 'DURATION': 10,
                          'MO_ATTRIBUTE': 'ueTraceFileSize', 'BURST_ID': '581',
                          'MO_PATH': 'ManagedElement=1,ENodeBFunction=1,PmEventService=1',
                          'MO_VALUES': [1010, 1020, 1000], SCHEDULED_TIMES_STRINGS: ["05:00:00"],
                          EXCLUDE_NODES_FROM: ["TOP_01", "CMIMPORT_03", "CMIMPORT_05", "CMIMPORT_08", "CMIMPORT_09",
                                               "CELLMGT_01", "CELLMGT_02"]},
            'CMSYNC_09': {SCHEDULED_DAYS: ["TUESDAY"], NUM_NODES: {ERBS: 1000}, 'BURST_RATE': 1000, 'DURATION': 10,
                          'MO_ATTRIBUTE': 'ueTraceFileSize', 'BURST_ID': '591',
                          'MO_PATH': "ManagedElement=1,ENodeBFunction=1,PmEventService=1",
                          "MO_VALUES": [1010, 1020, 1000], SCHEDULED_TIMES_STRINGS: ["05:00:00"],
                          EXCLUDE_NODES_FROM: ["TOP_01", "CMIMPORT_03", "CMIMPORT_05", "CMIMPORT_08", "CMIMPORT_09",
                                               "CELLMGT_01", "CELLMGT_02"]},
            'CMSYNC_10': {SCHEDULED_DAYS: ["WEDNESDAY"], NUM_NODES: {ERBS: 25},
                          SCHEDULED_TIMES_STRINGS: ["05:00:00"]},
            'CMSYNC_11': {SCHEDULED_DAYS: ["THURSDAY"], NUM_NODES: {ROUTER_6672: 1},
                          SCHEDULED_TIMES_STRINGS: ["05:00:00"]},
            'CMSYNC_15': {NUM_NODES: {ROUTER_6672: -1}, 'AVG_PER_NODE': 0.003,
                          'NOTIFICATION_INFO': "ROUTER_6000_AVC_BURST_MO_TYPE_SETTINGS"},
            'CMSYNC_19': {NUM_NODES: {RBS: 1}, SCHEDULED_TIMES_STRINGS: ["20:55:00"]},
            'CMSYNC_20': {NUM_NODES: {RNC: 1}, SCHEDULED_TIMES_STRINGS: ["23:55:00"]},
            'CMSYNC_21': {},
            'CMSYNC_22': {},
            'CMSYNC_24': {},
            'CMSYNC_25': {NUM_NODES: {ERBS: 1000, RADIONODE: 1000}, SCHEDULED_TIMES_STRINGS: ["23:00:00"],
                          NODE_FILTER: {'RadioNode': {'managed_element_type': ['ENodeB']}}},
        },
        "doc": {
            'DOC_01': {NUM_USERS: 20, USER_ROLES: ["OPERATOR"], SCHEDULE_SLEEP: 60 * 60}
        },
        "ebsl": {
            'EBSL_FILE_01': {},
            'EBSL_STREAM_01': {},
            'EBSL_01': {'CELLTRACE_EBSL_RETENTION': ('pmicCelltraceFileRetentionPeriodInMinutes', 4320)},
            'EBSL_02': {},
            'EBSL_03': {},
            'EBSL_04': {},
            'EBSL_05': {NUM_NODES: {ERBS: -1, RADIONODE: -1, MSRBS_V1: -1}, 'NUM_EVENTS': 1.0, 'NUM_COUNTERS': 1.0, USER_ROLES: ["PM_Operator"]},
            'EBSL_06': {NUM_NODES: {ERBS: -1, RADIONODE: -1, MSRBS_V1: -1}, 'NUM_EVENTS': 1.0, 'NUM_COUNTERS': 1.0, USER_ROLES: ["PM_Operator"]}
        },
        "ebsm": {
            'EBSM_01': {},
            'EBSM_02': {},
            'EBSM_03': {},
            'EBSM_04': {NUM_NODES: {SGSN: -1}, 'EBM_ROP_INTERVAL': 'ONE_MIN', 'NUM_EVENTS': 1.0,
                        'NUM_COUNTERS': 1.0, 'COUNTER_FILE_FORMAT': "TGPP_ENIQ_GZ", USER_ROLES: ["PM_Operator"]},
            'EBSM_05': {}
        },
        "em": {
            'EM_01': {SUPPORTED_NODE_TYPES: [RADIONODE], TOTAL_NODES: 100, NUM_USERS: 100,
                      NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}}, SCHEDULE_SLEEP: 60 * 30,
                      USER_ROLES: ['Element_Manager_Operator', 'OPERATOR']}
        },
        "enmcli": {
            'ENMCLI_01': {NUM_NODES: {ERBS: -1, RADIONODE: -1, RNC: -1, RBS: -1}, NUM_USERS: 1,
                          USER_ROLES: ['Cmedit_Administrator', 'Network_Explorer_Administrator'],
                          SCHEDULE_SLEEP: 60 * 60},
            'ENMCLI_02': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], TOTAL_NODES: 97, NUM_USERS: 97,
                          NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                          USER_ROLES: ['Cmedit_Administrator', 'Network_Explorer_Administrator'],
                          SCHEDULE_SLEEP: 15 * 60, EXCLUDE_NODES_FROM: ["TOP_01", 'CMIMPORT_09']},
            'ENMCLI_03': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], TOTAL_NODES: 2, NUM_USERS: 100,
                          'SCHEDULE_SLEEP': 900, 'enmcli_commands_list': "ENMCLI_COMMANDS",
                          USER_ROLES: ['Cmedit_Operator', 'Scripting_Operator', 'FM_Operator',
                                       'Lcm_Administrator', 'NodeSecurity_Operator', 'Autoprovisioning_Operator',
                                       'ADMINISTRATOR', 'SECURITY_ADMIN'], 'total_commands_sec': 0.5,
                          'percentage_cm_bas': 22.5, 'percentage_cm_std': 45, 'percentage_cm_adv': 22.5,
                          'percentage_alarm': 5, 'percentage_secadm': 5},
            'ENMCLI_04': {},
            'ENMCLI_05': {TOTAL_NODES: 4000, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], NUM_USERS: 1,
                          USER_ROLES: ['ADMINISTRATOR', 'Cmedit_Administrator', 'Network_Explorer_Administrator']}
        },
        "esm": {
            'ESM_01': {NUM_USERS: 40, USER_ROLES: ["ADMINISTRATOR"], SCHEDULE_SLEEP: 60 * 60, 'THREAD_QUEUE_TIMEOUT': 2 * 60 * 60},
            'ESM_02': {}
        },
        "fm": {
            'FM_0506': {NUM_NODES: {ERBS: -1, RADIONODE: -1, MGW: -1, SGSN: -1, ROUTER_6672: -1, MLTN: 0,
                                    RNC: -1, RBS: -1}, 'BURST_RATE': 200, USER_ROLES: ["FM_Administrator"], NUM_USERS: 1,
                        'SETUP_STEPS': {"ACK_ALARM": False, "CLEAR_ALARM": False, "CEASE_ALARM": True,
                                        "AUTO_ACK": True, "DELAYED_ACK": True}},
            'FM_01': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE, MGW, SGSN, ROUTER_6672, RNC, RBS, BSC, MSC_DB_BSP],
                      TOTAL_NODES: 60, 'BURST_RATE': 20.2, 'DURATION': 1860, SCHEDULE_SLEEP: 1800,
                      'ALARM_SIZE_DISTRIBUTION': [1000, 1000, 1000, 1000, 2000, 2000, 2000, 2000, 3000, 4000],
                      'ALARM_PROBLEM_DISTRIBUTION': [
                          ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                          ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                          ('TU Synch Reference Loss of Signal', 'major'),
                          ('TU Synch Reference Loss of Signal', 'major'),
                          ('TU Synch Reference Loss of Signal', 'major'), ('Link Failure', 'critical'),
                          ('Link Failure', 'critical'), ('Link Failure', 'critical'), ('', 'warning'),
                          ('', 'warning')]},
            'FM_02': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE, MGW, SGSN, ROUTER_6672, RNC, RBS, BSC, MSC_DB_BSP],
                      TOTAL_NODES: 300, 'BURST_RATE': 40, 'DURATION': 300, SCHEDULE_SLEEP: 900,
                      'ALARM_SIZE_DISTRIBUTION': [1000, 1000, 1000, 1000, 2000, 2000, 2000, 2000, 3000, 4000],
                      'ALARM_PROBLEM_DISTRIBUTION': [
                          ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                          ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                          ('TU Synch Reference Loss of Signal', 'major'),
                          ('TU Synch Reference Loss of Signal', 'major'),
                          ('TU Synch Reference Loss of Signal', 'major'), ('Link Failure', 'critical'),
                          ('Link Failure', 'critical'), ('Link Failure', 'critical'), ('', 'warning'),
                          ('', 'warning')]},
            'FM_03': {SUPPORTED_NODE_TYPES: [ERBS, RADIONODE, MGW, SGSN, ROUTER_6672, RNC, RBS, BSC, MSC_DB_BSP],
                      NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], TOTAL_NODES: 1000, 'BURST_RATE': 200, 'DURATION': 240,
                      'GSM_BURST_RATE': 350, 'GSM_DURATION': 1200, SCHEDULE_SLEEP: 10800,
                      'ALARM_SIZE_DISTRIBUTION': [1000, 1000, 1000, 1000, 2000, 2000, 2000, 2000, 3000, 4000],
                      'ALARM_PROBLEM_DISTRIBUTION': [
                          ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                          ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                          ('TU Synch Reference Loss of Signal', 'major'),
                          ('TU Synch Reference Loss of Signal', 'major'),
                          ('TU Synch Reference Loss of Signal', 'major'), ('Link Failure', 'critical'),
                          ('Link Failure', 'critical'), ('Link Failure', 'critical'), ('', 'warning'),
                          ('', 'warning')]},
            'FM_04': {},
            'FM_07': {},
            'FM_08': {TOTAL_NODES: 500, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE, ROUTER_6672], NUM_USERS: 23,
                      'NUM_USERS_1': 18, 'NUM_USERS_2': 5, USER_ROLES: ["FM_Operator"], SCHEDULE_SLEEP: 60 * 15},
            'FM_09': {TOTAL_NODES: 500, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE, ROUTER_6672], NUM_USERS: 35,
                      USER_ROLES: ["FM_Operator"], SCHEDULE_SLEEP: 60 * 15},
            'FM_10': {NUM_NODES: {}, NUM_USERS: 1, USER_ROLES: ["FM_Administrator"], SCHEDULED_TIMES_STRINGS: ["10:00:00"],
                      SCHEDULED_DAYS: ["THURSDAY"]},
            'FM_11': {NUM_USERS: 1, USER_ROLES: ["FM_Operator"], SCHEDULE_SLEEP: 60 * 60 * 2},
            'FM_12': {NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"],
                      'NUMBER_NBI_SUBSCRIPTIONS': 15, 'TIMEOUT': 2, TOTAL_NODES: 0, 'TIMEOUT_SUBSCRIPTION': 60 * 24,
                      'NBI_filters': ["LTE0", "LTE1", "LTE2", "LTE3", "LTE4", "LTE5"],
                      'CORBA_ENABLED': True},
            'FM_14': {TOTAL_NODES: 1, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], NUM_USERS: 4, USER_ROLES: ["FM_Administrator"],
                      SCHEDULED_TIMES_STRINGS: ["16:00:00"]},
            'FM_15': {TOTAL_NODES: 500, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE], NUM_USERS: 1, USER_ROLES: ["FM_Administrator"],
                      SCHEDULED_DAYS: ['WEDNESDAY'], SCHEDULED_TIMES_STRINGS: ["16:00:00"]},
            'FM_16': {'NUMBER_BNSI_CLIENTS': 10},
            'FM_17': {NUM_USERS: 1, NUM_NODES: {}, USER_ROLES: ["FM_Administrator"], SCHEDULED_TIMES_STRINGS: ["19:00:00"]},
            'FM_20': {NUM_NODES: {ERBS: -1, RADIONODE: -1, MGW: -1, SGSN: -1, ROUTER_6672: -1}, NUM_USERS: 2,
                      USER_ROLES: ["FM_Administrator"], SCHEDULE_SLEEP: 60 * 15},
            'FM_21': {NUM_USERS: 1, NUM_NODES: {}, SCHEDULE_SLEEP: 24 * 60 * 60,
                      USER_ROLES: ["FM_Administrator", "Cmedit_Administrator"]},
            'FM_22': {NUM_USERS: 1, USER_ROLES: ["FM_Administrator"]},
            'FM_23': {},
            'FM_24': {},
            'FM_25': {NUM_USERS: 5, NUM_NODES: {ERBS: 20, RADIONODE: 20, SGSN: 20, MGW: 20}, SCHEDULE_SLEEP: 60 * 60 * 24,
                      SCHEDULED_TIMES_STRINGS: ["10:00:00"], 'SLEEP_TIME': 1200,
                      USER_ROLES: ["FM_Operator", "NetworkLog_Administrator", "Cmedit_Operator"]},
            'FM_26': {NUM_USERS: 1, NUM_NODES: {}, USER_ROLES: ["FM_Administrator"],
                      SCHEDULED_TIMES_STRINGS: ["10:00:00"]},
        },
        "fmx": {
            'FMX_01': {SCHEDULE_SLEEP: 60 * 60, USER_ROLES: ["FMX_Administrator"]},
            'FMX_05': {NUM_NODES: {ERBS: 12}, SCHEDULE_SLEEP: 60 * 60,
                       'MAINTENANCE_MODES': ['MARK', 'NMS', 'NMSandOSS']}
        },
        "ha": {
            'HA_01': {NUM_NODES: {ERBS: 50}}
        },
        "lcm": {
            'LCM_01': {}
        },
        "logviewer": {
            'LOGVIEWER_01': {SCHEDULE_SLEEP: 1800, NUM_USERS: 50, USER_ROLES: ["OPERATOR"], 'SEARCH_TERM': "all errors"}
        },
        "migration": {
            'MIGRATION_01': {},
            'MIGRATION_02': {}
        },
        "netex": {
            'NETEX_01': {NUM_NODES: {ERBS: -1}, NUM_USERS: 99,
                         USER_ROLES: ["Network_Explorer_Operator"], SCHEDULE_SLEEP: 60 * 30},
            'NETEX_02': {NUM_NODES: {ERBS: -1, RADIONODE: -1, RNC: -1, RBS: -1, SGSN: -1, MGW: -1,
                                     MSRBS_V1: -1}, 'NUM_COLLECTIONS': 50, SCHEDULE_SLEEP: 60 * 60,
                         USER_ROLES: ["Network_Explorer_Administrator"], 'NODES_PER_COLLECTION': 100},
            'NETEX_03': {NUM_NODES: {ERBS: -1}, NUM_USERS: 1,
                         USER_ROLES: ['Network_Explorer_Administrator']},
            'NETEX_04': {NUM_USERS: 2, USER_ROLES: ['Network_Explorer_Administrator', 'Cmedit_Operator'],
                         SCHEDULE_SLEEP: 60 * 60}
        },
        "network": {
            'NETWORK_01': {},
            'NETWORK_02': {},
            'NETWORK_03': {},
            'NETWORK_04': {},
            'NETWORK_05': {},
            'NETWORK_06': {},
            'NETWORK_07': {},
            'NETWORK_08': {},
            'NETWORK_09': {},
            'NETWORK_10': {}
        },
        "nhc": {
            'NHC_01': {SCHEDULE_SLEEP: 60 * 60, SUPPORTED_NODE_TYPES: [ERBS, MGW, RNC, RBS],
                       TOTAL_NODES: 1000, NUM_USERS: 1, USER_ROLES: ["Nhc_Operator"]}
        },
        "nhm": {
            'NHM_SETUP_01_02': {},
            'NHM_01_02': {TOTAL_NODES: 4000, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE],
                          NODE_FILTER: {RADIONODE: {'managed_element_type': ['ENodeB']}},
                          'MO_VALUES': {'EUtranCellFDD': 3}, 'BATCH_MO_SIZE': 150, USER_ROLES: ["NHM_Administrator"],
                          'NUM_KPIS_01': 7, 'NUM_KPIS_02': 18, 'REPORTING_OBJECT_01': ['ENodeBFunction'],
                          'REPORTING_OBJECT_02': ['EUtranCellFDD', 'EUtranCellTDD']},
            'NHM_01': {},
            'NHM_02': {},
            'NHM_03': {'NUM_ADMINS': 3, 'NUM_OPERATORS': 2, SCHEDULED_TIMES_STRINGS: ["00:10:00", "8:10:00", "16:10:00"],
                       'ADMIN_ROLE': ["NHM_Administrator"], 'OPERATOR_ROLE': ["NHM_Operator"],
                       'REPORTING_OBJECT': ['EUtranCellFDD', 'EUtranCellTDD']},
            'NHM_04': {TOTAL_NODES: 4000, 'OPERATOR_ROLE': ["NHM_Operator"], 'NUM_OPERATORS': 2, 'NUMBER_OF_KPIS': 25,
                       SCHEDULE_SLEEP: 15 * 60, 'WIDGETS': ["NodesBreached", "WorstPerforming", "MostProblematic",
                                                            "NetworkOperationalState", "NetworkSyncStatus"]},
            'NHM_05': {TOTAL_NODES: 20, 'NUM_ADMINS': 1, 'NUM_OPERATORS': 1, SCHEDULE_SLEEP: 15 * 60,
                       'ADMIN_ROLE': ["NHM_Administrator"],
                       'OPERATOR_ROLE': ["NHM_Operator"], 'REPORTING_OBJECT': 'EUtranCellFDD'},
            'NHM_06': {TOTAL_NODES: 20, 'NUM_ADMINS': 1, 'NUM_OPERATORS': 4, SCHEDULE_SLEEP: 15 * 60,
                       'ADMIN_ROLE': ["NHM_Administrator"],
                       'OPERATOR_ROLE': ["NHM_Operator"], 'REPORTING_OBJECT': 'EUtranCellFDD'},
            'NHM_07': {TOTAL_NODES: 20, 'NUM_ADMINS': 1, 'NUM_OPERATORS': 4, SCHEDULE_SLEEP: 15 * 60,
                       'ADMIN_ROLE': ["NHM_Administrator"],
                       'OPERATOR_ROLE': ["NHM_Operator"], 'REPORTING_OBJECT': 'ENodeBFunction'},
            'NHM_08': {TOTAL_NODES: 20, 'NUM_ADMINS': 5, 'NUM_OPERATORS': 5, SCHEDULE_SLEEP: 60 * 60,
                       'ADMIN_ROLE': ["NHM_Administrator"],
                       'OPERATOR_ROLE': ["NHM_Operator"]},
            'NHM_09': {TOTAL_NODES: 4000, 'OPERATOR_ROLE': ['NHM_Operator'], 'NUM_OPERATORS': 5, 'NUMBER_OF_KPIS': 1,
                       SCHEDULE_SLEEP: 60 * 60, 'WIDGETS': ["NodesBreached", "WorstPerforming"]},
            'NHM_10': {TOTAL_NODES: 4000, USER_ROLES: ['NHM_Operator'], 'NUM_OPERATORS': 2, SCHEDULE_SLEEP: 60 * 60},
            'NHM_11': {TOTAL_NODES: 4000, USER_ROLES: ['NHM_Operator'], 'NUM_OPERATORS': 1, 'NUMBER_OF_KPIS': 4,
                       SCHEDULE_SLEEP: 60 * 60}
        },
        "nodecli": {
            'NODECLI_01': {NUM_USERS: 100, USER_ROLES: ['NodeCLI_Administrator', 'OPERATOR'],
                           TOTAL_NODES: 100, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE, ROUTER_6672]}
        },
        "nodesec": {
            'NODESEC_01': {NUM_NODES: {ERBS: 1000}, 'NUM_BATCHES': 10},
            'NODESEC_02': {NUM_NODES: {ERBS: 500}, 'NUM_BATCHES': 5},
            'NODESEC_03': {'TEARDOWN': False, NUM_NODES: {ERBS: -1, MGW: -1}},
            'NODESEC_04': {'TEARDOWN': False, NUM_NODES: {ERBS: -1, MGW: -1}},
            'NODESEC_05': {},
            'NODESEC_06': {},
            'NODESEC_08': {NUM_NODES: {RADIONODE: -1, MSRBS_V1: 225, SGSN: 20, EPG: 5, ROUTER_6672: 50},
                           TOTAL_NODES: 900, NUM_USERS: 10, 'NUM_NODES_MAX_PER_USER': 90,
                           'SNMP_VERSION': 'SNMP_V3', 'NUM_BATCHES': 90},
            'NODESEC_09': {NUM_NODES: {SGSN: 80}, 'NUM_BATCHES': 5, 'ALGORITHM': 'RSA_1024'},
            'NODESEC_10': {NUM_NODES: {SGSN: 80}, 'NUM_BATCHES': 5, 'ALGORITHM': 'RSA_1024'},
            'NODESEC_11': {NUM_NODES: {ERBS: -1, MGW: -1, RADIONODE: -1}, 'CERTS': ['OAM']},
            'NODESEC_12': {NUM_NODES: {ERBS: -1, MGW: -1, RADIONODE: -1}, 'CERTS': ['OAM']},
            'NODESEC_13': {NUM_NODES: {ERBS: -1, MGW: -1, RADIONODE: -1}, 'CERTS': ['OAM']},
            'NODESEC_14': {NUM_NODES: {ERBS: -1, MGW: -1, RADIONODE: -1}, 'CERTS': ['OAM']},
            'NODESEC_15': {NUM_NODES: {}, NUM_USERS: 20, }
        },
        "nvs": {
            'NVS_01': {USER_ROLES: ['ADMINISTRATOR'], NUM_NODES: {ERBS: -1, RADIONODE: -1, RadioTNode: -1}},
            'NVS_02': {USER_ROLES: ['ADMINISTRATOR'], NUM_NODES: {ERBS: -1, RADIONODE: -1, RadioTNode: -1}}
        },
        "parmgt": {
            'PARMGT_01': {NUM_USERS: 14, USER_ROLES: ["Parameter_Management_Administrator", "Cmedit_Administrator"],
                          NUM_NODES: {RADIONODE: 1400}, SCHEDULE_SLEEP: 60 * 15},
            'PARMGT_02': {NUM_USERS: 2, USER_ROLES: ["Parameter_Management_Administrator"],
                          SCHEDULE_SLEEP: 24 * 60 * 60, "NUM_PARAMETER_SETS": 5,
                          "MAX_NUM_PARAMETER_SETS": 1000}
        },
        "pm": {
            'PM_01': {},
            'PM_02': {NUM_NODES: {ERBS: -1}, 'NUM_COUNTERS': 1.0, USER_ROLES: ['Cmedit_Administrator', "PM_Operator"], 'CBS': True, 'POLL_SCANNERS': True},
            'PM_03': {NUM_NODES: {ERBS: -1}, 'NUM_EVENTS': 1.0, USER_ROLES: ['Cmedit_Administrator', "PM_Operator"], 'CBS': True, 'POLL_SCANNERS': True},
            'PM_04': {USER_ROLES: ["PM_Operator"], SCHEDULE_SLEEP: 60 * 60 * 24, 'SYS_DEF_SUB_PATTERN': 'CCTR'},
            'PM_06': {NUM_NODES: {}, NUM_USERS: 100, USER_ROLES: ["PM_Operator"], 'CELLTRACE_SUPPORTED_NODE_TYPES': ["ERBS", "MSRBS_V2", "RadioNode"],
                      'STATS_UNSUPPORTED_NODE_TYPES': ["TCU02", "SIU02", "FRONTHAUL_6080", "EPG", "vEPG", "WMG", "vWMG", "MINI-LINK-Outdoor", "MINI-LINK-Indoor"]},
            'PM_11': {NUM_NODES: {ERBS: -1}, 'NUM_COUNTERS': 0.1, USER_ROLES: ['Cmedit_Administrator', "PM_Operator"], SCHEDULE_SLEEP: 60 * 60 * 6, 'OFFSET': 60 * 60 * 6, 'POLL_SCANNERS': True},
            'PM_12': {'CLOUD_SUPPORTED': False, SCHEDULE_SLEEP: 60 * 15, 'DEPENDENT_PROFILE': 'PM_13',
                      'ENIQ_DIR_NAME': "/pmlinksEvents1"},
            'PM_13': {'CLOUD_SUPPORTED': False, SCHEDULE_SLEEP: 60 * 15, 'DEPENDENT_PROFILE': 'PM_12',
                      'ENIQ_DIR_NAME': "/pmlinks1"},
            'PM_15': {'POLLING_AND_MASTER_RETENTION': ("scannerPollingIntervalMinutes", 15)},
            'PM_16': {USER_ROLES: ["PM_Operator"], 'USER_ROLES_CM': ["ADMINISTRATOR"],
                      'UE_INFO': {"type": "IMSI", "value": "27202"}, 'INTERFACE_TYPES': {'SGSN': [], 'ENODEB': ["s1"]}},
            'PM_17': {'PM_NBI_RETENTION_PARAMETERS': {'STATS_RETENTION': ("pmicStatisticalFileRetentionPeriodInMinutes", 4320), 'CELLTRACE_RETENTION': ("pmicCelltraceFileRetentionPeriodInMinutes", 180),
                                                      'UE_TRACE_RETENTION': ("pmicUeTraceFileRetentionPeriodInMinutes", 360), 'CTUM_RETENTION': ("pmicCtumFileRetentionPeriodInMinutes", 360),
                                                      'EBM_RETENTION': ("pmicEbmFileRetentionPeriodInMinutes", 180), 'CELL_TRAFFIC_RETENTION': ("pmicCellTrafficFileRetentionPeriodInMinutes", 180),
                                                      'UETR_RETENTION': ("pmicUetrFileRetentionPeriodInMinutes", 180), 'GPEH_RETENTION': ("pmicGpehFileRetentionPeriodInMinutes", 180)}, SCHEDULE_SLEEP: 60 * 60 * 24},
            'PM_19': {USER_ROLES: ["PM_Operator"], 'USER_ROLES_CM': ["ADMINISTRATOR"], 'SYS_DEF_SUB_PATTERN': 'CTUM',
                      'UE_INFO': {"type": "IMSI", "value": "27208"}, SCHEDULE_SLEEP: 60 * 60 * 24},
            'PM_20': {NUM_NODES: {SGSN: -1}, 'ROP_STR': 'ONE_MIN', 'NUM_EVENTS': 1.0, USER_ROLES: ["PM_Operator"]},
            'PM_22': {},
            'PM_24': {USER_ROLES: ["PM_Operator"], 'USER_ROLES_CM': ["ADMINISTRATOR"], 'UE_INFO': {"type": "IMSI", "value": "27201"}},
            'PM_25': {NUM_NODES: {MGW: -1}, 'NUM_COUNTERS': 20000, USER_ROLES: ["PM_Operator"]},
            'PM_26': {USER_ROLES: ["PM_NBI_Operator"], 'ROP_INTERVAL': 15, SCHEDULE_SLEEP: 15 * 60,
                      'SFTP_FETCH_TIME_IN_MINS': 15, 'N_SFTP_THREADS': 10,
                      'DATA_TYPES': ['PM_STATISTICAL', 'PM_CELLTRACE', 'PM_CTUM', 'PM_EBM', 'PM_UETR', 'PM_EBSL',
                                     'PM_GPEH', 'PM_UETRACE', 'PM_CTR', 'TOPOLOGY_*']},
            'PM_27': {USER_ROLES: ["PM_Operator"], SCHEDULE_SLEEP: 60 * 60 * 24, 'SYS_DEF_SUB_PATTERN': 'EPG'},
            'PM_28': {},
            'PM_29': {NUM_NODES: {RNC: -1}, 'NUM_EVENTS': 1.0, USER_ROLES: ["PM_Operator"]},
            'PM_30': {NUM_NODES: {RBS: -1}, 'NUM_COUNTERS': 1.0, USER_ROLES: ["PM_Operator"], SCHEDULE_SLEEP: 60 * 2,
                      'SYS_DEF_SUB_PATTERN': 'RBS'},
            'PM_31': {NUM_NODES: {RNC: -1}, 'NUM_COUNTERS': 1.0, USER_ROLES: ["PM_Operator"], SCHEDULE_SLEEP: 60 * 2,
                      'SYS_DEF_SUB_PATTERN': 'RNC Primary'},
            'PM_32': {NUM_NODES: {ROUTER_6672: -1}, 'NUM_COUNTERS': 1.0, USER_ROLES: ["PM_Operator"]},
            'PM_33': {},
            'PM_34': {SCHEDULED_TIMES_STRINGS: ["18:25:00"]},
            'PM_35': {'NOTE': 'MUST BE EXECUTED MANUALLY'},
            'PM_36': {'NOTE': 'Covered by cmexport_06', 'PROJECT': '17B.1'},
            'PM_37': {'NOTE': 'Covered by cmexport_06', 'PROJECT': '17B.1'},
            'PM_38': {NUM_NODES: {RADIONODE: -1}, 'NUM_COUNTERS': 1.0, USER_ROLES: ['Cmedit_Administrator', "PM_Operator"], 'CBS': True, 'POLL_SCANNERS': True,
                      'MO_CLASS_COUNTERS_EXCLUDED': ['EUtranCellFDD', 'EUtranCellTDD']},
            'PM_39': {},
            'PM_40': {NUM_NODES: {SGSN: -1}, 'NUM_COUNTERS': 1.0, USER_ROLES: ["PM_Operator"]},
            'PM_41': {},
            'PM_42': {NUM_NODES: {RADIONODE: -1}, 'NUM_EVENTS': 1.0, USER_ROLES: ['Cmedit_Administrator', "PM_Operator"], 'CBS': True, 'POLL_SCANNERS': True,
                      NODE_FILTER: {RADIONODE: {"managed_element_type": ["ENodeB"]}}},
            'PM_43': {'POLL_SCANNERS': True},
            'PM_44': {},
            'PM_45': {},
            'PM_46': {NUM_NODES: {RNC: -1}, 'NUM_EVENTS': 1.0, USER_ROLES: ["PM_Operator"], 'CBS': True},
            'PM_47': {NUM_NODES: {RNC: -1}, 'NUM_EVENTS': 1.0, USER_ROLES: ["PM_Operator"],
                      'IMSI': [{"type": "IMSI", "value": "123546"}, {"type": "IMSI", "value": "234567"}, {"type": "IMSI", "value": "345678"},
                               {"type": "IMSI", "value": "456789"}, {"type": "IMSI", "value": "567890"}, {"type": "IMSI", "value": "122133213212144"},
                               {"type": "IMSI", "value": "2432342343"}, {"type": "IMSI", "value": "34234324324"}, {"type": "IMSI", "value": "2432423425"},
                               {"type": "IMSI", "value": "546546546546"}, {"type": "IMSI", "value": "4765765765"}, {"type": "IMSI", "value": "888586"},
                               {"type": "IMSI", "value": "65867885"}, {"type": "IMSI", "value": "67876878"}, {"type": "IMSI", "value": "6867867876"},
                               {"type": "IMSI", "value": "67876876867"}]},
            'PM_48': {NUM_NODES: {RADIONODE: -1}, 'NUM_COUNTERS': 0.1, USER_ROLES: ['Cmedit_Administrator', "PM_Operator"], SCHEDULE_SLEEP: 60 * 60 * 24, 'OFFSET': 60 * 60 * 6, 'POLL_SCANNERS': True,
                      NODE_FILTER: {RADIONODE: {"managed_element_type": ["ENodeB"]}}, 'MO_CLASS_COUNTERS_EXCLUDED': ['EUtranCellFDD', 'EUtranCellTDD']},
            'PM_49': {},
            'PM_50': {NUM_NODES: {MTAS: -1}, USER_ROLES: ["PM_Operator"]},
            'PM_51': {NUM_NODES: {RBS: -1}, 'NUM_EVENTS': 1.0, USER_ROLES: ["PM_Operator"], 'CBS': True},
            'PM_52': {NUM_NODES: {RADIONODE: -1, ERBS: -1}, 'NODES_TO_FIND': {RADIONODE: 6, ERBS: 1}, USER_ROLES: ['Cmedit_Administrator', "PM_Operator"], SCHEDULED_TIMES_STRINGS: ["00:00:00"]},
            'PM_53': {NUM_NODES: {RNC: -1}, 'NUM_EVENTS': '1.0', 'ROP_STR': 'ONE_MIN', USER_ROLES: ["PM_Operator"], 'CBS': True},
            'PM_54': {NUM_NODES: {MLTN: -1}, 'NUM_EVENTS': 1.0, USER_ROLES: ["PM_Operator"]},
            'PM_55': {NUM_NODES: {MINILINK_6352: -1}, 'NUM_EVENTS': 1.0, USER_ROLES: ["PM_Operator"]},
            'PM_56': {USER_ROLES: ["PM_Operator"], SCHEDULE_SLEEP: 60 * 60 * 24, 'SYS_DEF_SUB_PATTERN': 'SIU02'},
            'PM_57': {USER_ROLES: ["ULSA_Operator"], SCHEDULE_SLEEP: 60 * 60 * 23},
            'PM_58': {USER_ROLES: ["PM_Operator"], SCHEDULE_SLEEP: 60 * 60 * 24, 'SYS_DEF_SUB_PATTERN': 'TCU02'},
            'PM_59': {USER_ROLES: ["PM_Operator"], SCHEDULE_SLEEP: 60 * 60 * 24, 'SYS_DEF_SUB_PATTERN': 'ERBS'},
            'PM_60': {USER_ROLES: ["PM_Operator"], SCHEDULE_SLEEP: 60 * 60 * 24, 'SYS_DEF_SUB_PATTERN': 'RadioNode'},
            'PM_62': {NUM_NODES: {BSC: -1}, USER_ROLES: ["PM_Operator"], 'CBS': True},
            'PM_63': {NUM_NODES: {MSC_DB_BSP: -1}, USER_ROLES: ["PM_Operator"], 'CBS': True},
            'PM_64': {NUM_NODES: {MSC_BC_BSP: -1}, USER_ROLES: ["PM_Operator"], 'CBS': True},
            'PM_65': {NUM_NODES: {MSC_BC_IS: -1}, USER_ROLES: ["PM_Operator"], 'CBS': True},
            'PM_99': {}
        },
        "secui": {
            'SECUI_01': {'NUMBER_OF_SECURITY_ADMINS': 10, 'NUMBER_OF_USERS_TO_CREATE': 2500,
                         'NUMBER_OF_ROLES_TO_ASSIGN': 5, 'THREAD_QUEUE_TIMEOUT': 2 * 60 * 60},
            'SECUI_02': {'NUMBER_OF_USERS': 30, 'NUMBER_OF_ROLES': 20, SCHEDULE_SLEEP: 24 * 60 * 60},
            'SECUI_04': {SCHEDULE_SLEEP: 60, 'MAXIMUM_ACTIVE_USERS': 1000},
            'SECUI_05': {NUM_USERS: 34, USER_ROLES: ["SECURITY_ADMIN"], 'SECUI_01_KEY': 'SECUI_01',
                         'CREATED_ROLE_COUNT': 25},
            'SECUI_06': {'PKI_NAME': 'Secui_Six_{0}'},
            'SECUI_07': {'NUM_TARGET_GROUPS': 1970, TOTAL_NODES: 1, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE, MLTN]},
            'SECUI_08': {SCHEDULE_SLEEP: 60 * 24 * 60, 'NUM_TARGET_GROUPS': 30},
            'SECUI_09': {SCHEDULE_SLEEP: 60 * 24 * 60},
            'SECUI_10': {NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], NUM_NODES: {RADIONODE: -1},
                         SCHEDULE_SLEEP: 60 * 24 * 60},
            'SECUI_11': {},
            'SECUI_12': {NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], NUM_NODES: {RADIONODE: -1},
                         SCHEDULE_SLEEP: 60 * 24 * 60}
        },
        "shm": {
            'SHM_SETUP': {NUM_NODES: {ERBS: -1, MGW: -1, RADIONODE: -1, MLTN: -1, ROUTER_6672: -1}},
            'SHM_01': {NUM_NODES: {ERBS: 1000}, SCHEDULED_TIMES_STRINGS: ["12:30:00"],
                       "HOUR": 12, "MINUTE": 30, "SECOND": 0},
            'SHM_02': {TOTAL_NODES: 1000, SCHEDULED_TIMES_STRINGS: ["14:00:00"],
                       NUM_NODES: {RADIONODE: 1000}, NODE_FILTER: {RADIONODE: {'managed_element_type': ["ENodeB"]}}},
            'SHM_03': {'NODES_PER_HOST': 80, SCHEDULED_TIMES_STRINGS: ["06:30:00"], NUM_NODES: {ERBS: 1000},
                       SCHEDULED_DAYS: ['WEDNESDAY'], 'MAX_NODES': 1000,
                       "SHM_JOB_SCHEDULED_TIME_STRINGS": ["07:00:00"]},

            'SHM_04': {NUM_NODES: {ERBS: 1000}, SCHEDULED_TIMES_STRINGS: ["11:00:00"], 'TIMEOUT': 1800,
                       SCHEDULED_DAYS: ['WEDNESDAY']},
            'SHM_05': {'NODES_PER_HOST': 100, SCHEDULED_TIMES_STRINGS: ["04:30:00"],
                       NUM_NODES: {RADIONODE: 500}, SCHEDULED_DAYS: ['THURSDAY'], 'MAX_NODES': 500,
                       NODE_FILTER: {RADIONODE: {'managed_element_type': ["ENodeB"]}},
                       "SHM_JOB_SCHEDULED_TIME_STRINGS": ["05:00:00", "07:00:00"]},
            'SHM_06': {NUM_USERS: 20, TOTAL_NODES: 20, SUPPORTED_NODE_TYPES: [ERBS, RADIONODE, MLTN],
                       SCHEDULE_SLEEP: 60 * 60, USER_ROLES: ["Shm_Administrator", "Cmedit_Administrator"],
                       EXCLUDE_NODES_FROM: ['SHM_01', 'SHM_18', 'SHM_03'],
                       NODE_FILTER: {RADIONODE: {'managed_element_type': ["ENodeB"]}}},
            'SHM_07': {NUM_USERS: 80, NUM_NODES: {ERBS: -1, RADIONODE: -1}, SCHEDULE_SLEEP: 3000,
                       USER_ROLES: ["Shm_Administrator", "Network_Explorer_Administrator"]},
            'SHM_17': {NUM_NODES: {ERBS: 1000}, SCHEDULED_TIMES_STRINGS: ["20:00:00"], SCHEDULED_DAYS: ['FRIDAY'],
                       "DEFAULT": False},
            'SHM_18': {NUM_NODES: {ERBS: 100}, SCHEDULED_TIMES_STRINGS: ["19:00:00"],
                       SCHEDULED_DAYS: ['SUNDAY']},
            'SHM_19': {NUM_NODES: {}, SCHEDULED_TIMES_STRINGS: ["19:00:00"], SCHEDULED_DAYS: ['THURSDAY']},
            'SHM_20': {NUM_NODES: {}, SCHEDULED_TIMES_STRINGS: ["19:00:00"], SCHEDULED_DAYS: ['FRIDAY']},
            'SHM_21': {NUM_NODES: {}, SCHEDULED_TIMES_STRINGS: ["19:00:00"], SCHEDULED_DAYS: ['SATURDAY']},
            'SHM_22': {NUM_NODES: {RADIONODE: 1000}, SCHEDULED_TIMES_STRINGS: ["21:00:00"], SCHEDULED_DAYS: ['FRIDAY'],
                       "DEFAULT": True, NODE_FILTER: {RADIONODE: {'managed_element_type': ["ENodeB"]}}},
            'SHM_23': {NUM_NODES: {MLTN: 1000}, SCHEDULED_TIMES_STRINGS: ["03:00:00"],
                       SCHEDULED_DAYS: ['SUNDAY']},
            'SHM_24': {'NODES_PER_HOST': 125, NUM_NODES: {MLTN: 500}, SCHEDULED_TIMES_STRINGS: ["08:00:00"],
                       SCHEDULED_DAYS: ['SUNDAY'], 'MAX_NODES': 500},
            'SHM_25': {'NODES_PER_HOST': 80, NUM_NODES: {ERBS: -1}, 'MAX_NODES': 1000},
            'SHM_26': {NUM_NODES: {ERBS: 100}},
            'SHM_28': {NUM_NODES: {ERBS: 100}, SCHEDULED_TIMES_STRINGS: ["20:00:00"], SCHEDULED_DAYS: ['WEDNESDAY']},
            'SHM_34': {NUM_NODES: {ROUTER_6672: 1000}, SCHEDULED_TIMES_STRINGS: ["23:30:00"]}
        },
        "top": {
            'TOP_01': {NUM_NODES: {ERBS: 75, RADIONODE: 25}, NUM_USERS: 100,
                       USER_ROLES: ["Topology_Browser_Administrator"], SCHEDULE_SLEEP: 60 * 15,
                       NODE_FILTER: {"RadioNode": {"managed_element_type": ["ENodeB", "ENodeB|NodeB"]}},
                       EXCLUDE_NODES_FROM: ["CMSYNC_02", "CMSYNC_04", "CMSYNC_06", "CMSYNC_08", "CMSYNC_09",
                                            "ENMCLI_02"]}
        }
    }
}
