package BasicConfig;


/**
* BasicConfig/IterRef.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_K.idl
* Tuesday, May 22, 2018 12:36:12 PM GMT+01:00
*/

public final class IterRef implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;

  public IterRef ()
  {
  } // ctor

  public IterRef (int _id)
  {
    id = _id;
  } // ctor

} // class IterRef
