package BasicConfig;


/**
* BasicConfig/MORef.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configuration_K.idl
* Tuesday, May 22, 2018 12:36:12 PM GMT+01:00
*/

public final class MORef implements org.omg.CORBA.portable.IDLEntity
{
  public long oid = (long)0;
  public BasicConfig.BasicConfiguration cid = null;
  public String type = null;

  public MORef ()
  {
  } // ctor

  public MORef (long _oid, BasicConfig.BasicConfiguration _cid, String _type)
  {
    oid = _oid;
    cid = _cid;
    type = _type;
  } // ctor

} // class MORef
